### ISSUE TITLE
[FR] Ability to override print cancel 

### ISSUE THREAD

**Issue by agravelot** [jordanruthe/KlipperScreen#1005]
**Is your feature request related to a problem? Please describe.**

When i cancel a failed print on mainsail, i do have a macro which cleanly park my toolhead when possible.
But if i cancel it from KlipperScreen, i do not have the same behavior, toolhead is stale.

The cancel behavior seems to be hard-coded to klippy ws, having a solution to customize it would be nice.

**Describe the solution you'd like**
I would like to be able to define it like any menu entries.
https://github.com/jordanruthe/KlipperScreen/blob/master/ks_includes/defaults.conf

**Describe alternatives you've considered**
Or maybe define it inside klipper config.

**Additional context**

**Comment by alfrix** [comment]
use a cancel_print macro it will work in all frontends

see for example https://github.com/mainsail-crew/mainsail-config/blob/e4976f616e2c779218cdb0c60d2b967c917b6ec4/client.cfg#LL49C6-L49C6
