### ISSUE TITLE
[BUG] Memory leak

### ISSUE THREAD

**Issue by mpaw** [jordanruthe/KlipperScreen#1008]
**Describe the bug**
KlipperScreen seems to have a memory leak and is causing one of the RPi cores to be pinged at 100%. Only way to resolve it seems to be to restart the KlipperScreen process or reboot the RPi. The touch screen is somewhat unresponsive and has a 5 second (or more) delay between when a touch happens and when it executes that event. This happened after running only a single print. I had the printer/raspberry pi turned off for over a day as can be seen in the log I am including. So this memory leak happened in hours. I trimmed the log to just the last few days.

**To Reproduce**
I just triggered a print and tweaked z-offset while it was printing. Nothing different from any other time.

**Expected behavior**
Memory to not leak and CPU not be pinged at 100%

**Screenshots**
<img width="794" alt="image" src="https://github.com/jordanruthe/KlipperScreen/assets/5834637/05c22b42-9025-4bd0-934a-84d916691849">

**Logfile**
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/11712900/KlipperScreen.log)

**Comment by alfrix** [comment]
it should be fixed in v0.3.2 1813533becd0eaa138183ddc262e39e12905d431
