### ISSUE TITLE
[BUG] Wrong print file dialog after switching printers, it shows the dialog from the first printer opened. 

### ISSUE THREAD

**Issue by simpat1zq** [jordanruthe/KlipperScreen#1012]
From my issue I opened for the memory leak, I think that the fix for that might be causing this bug, but that's just a guess. Here are the steps to reproduce:

Start Klipperscreen pointing to Printer A. 
Tap Print
Tap switch printers, and switch to Printer B. 
Tap Print. 

The print dialog should be for printer B, but it is not. It just loads the print dialog for printer A. Not sure if the same thing is happening for other dialogs or not. 

EDIT: I forgot to mention, that once I do those steps, I can no longer print at all. Tapping print on a file does nothing. I have to restart KS and everything works great, until I switch printers.

**Comment by alfrix** [comment]
since i don't have multiple printers i don't test that, but that sounds very bad, i will give it priority

**Comment by simpat1zq** [comment]
This is supposed let you have a dummy printer. I've never used it, but that might allow you to test some stuff.
