### ISSUE TITLE
[BUG] The language switching function is damaged.

### ISSUE THREAD

**Issue by bigtreetech** [jordanruthe/KlipperScreen#1015]
**Describe the bug**
* change the language to Chinese in the settings interface. Only some entries in the interface have been changed to Chinese, while others remain in English. And after reboot, all entries are restored to the default English. (Tested other languages and had the same problem)

**To Reproduce**
1. Go to `Congifuration->Settings->Language`
2. Choose a language other than English
3. It is easy to find that there is no language switching for many entries
4. Restore all entries to default English after reboot

**Comment by bigtreetech** [comment]
@alfrix Hi. After switching languages, all entries can be switched to the set language normally, This problem has been fixed. 

However, the issue of automatically changing back to the default English after reboot still exists.

**Comment by mehmetsutas** [comment]
Confirmed. Language setting is not saved. Even after saving the settings reboot automatically enables English.

**Comment by alfrix** [comment]
sorry i did not notice the response that it wasn't fully fixed, i will look into it
