### ISSUE TITLE
[BUG] Menus not fitting the display

### ISSUE THREAD

**Issue by edubbwa** [jordanruthe/KlipperScreen#1034]
After updating to v0.3.3-1 the display layout changed and no longer fits the display

All other prior versions fit the display correctly

[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/11950099/KlipperScreen.log)

![20230704_084622](https://github.com/jordanruthe/KlipperScreen/assets/49591889/cd847398-a33d-4570-9daf-5350f5780f18)
![20230704_084632](https://github.com/jordanruthe/KlipperScreen/assets/49591889/f2cc789a-fba1-4c21-8b61-4f65fc13f117)
![20230704_084647](https://github.com/jordanruthe/KlipperScreen/assets/49591889/d5cdd499-a2d5-4980-bc16-c950b4020c9d)

**Comment by alfrix** [comment]
beware that you have entries that are deprecated in your config, i advise you to cleanup your klipperscreen.conf to something like this: 
```
[printer SoVoL - SV01 ]
moonraker_host = 192.168.4.102
moonraker_port = 7126
moonraker_api_key = [redacted]
titlebar_items = MCU, Pi
extrude_distances = 10, 15, 25, 50

[printer Ender 3 Pro]
moonraker_host = 192.168.4.102
moonraker_port = 7125
moonraker_api_key = [redacted]
extrude_distances = 10, 15, 25, 50

[preheat PLA-1]
bed = 65
extruder = 215

[preheat PLA-2]
bed = 60
extruder = 210

[preheat PETG]
bed = 70
extruder = 230

#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# language = en
#~# 24htime = False
#~# font_size = small
#~# show_heater_power = True
#~# print_sort_dir = date_desc
#~#

```
