### ISSUE TITLE
Using KlipperScreen to move causes printer to change to relative movement mode

### ISSUE THREAD

**Issue by michelluccote** [jordanruthe/KlipperScreen#106]
When I cancel a print and move the nozzle up 25 using KlipperScreen it runs the command G91 and G1 Z25. It then leaves the printer in G91 mode. I don't know if this is expected but my start code found in Cura (which is the default code for Ender 3s) appears to assume the printer will be in G90 mode (absolute movement). This causes the printer to issue the following error if I start a new job right after doing one of these cancel and move operations:

$ CANCEL_PRINT
20:03:23
// action:paused
20:03:23
// action:cancel
20:03:32
$ G91
G1 Z25
20:03:32
$ G91
G1 Z25
20:03:57
$ SDCARD_PRINT_FILE FILENAME="CE3PRO_Mono_X Platter Holder Bracket.gcode"
20:03:57
File opened:CE3PRO_Mono_X Platter Holder Bracket.gcode Size:4498446
20:03:57
File selected
20:05:44
!! Move out of range: 170.200 345.000 17.715 [82.762]
20:05:52

If I simply do a G90 and restart the print all goes well. Ideally KlipperScreen should find what mode it is in, do the move and revert back to the same state as before.

**Comment by ShohninDmitriy** [comment]
panels/move.py   

print("%s\n%s %s%s\n**%s**" % (KlippyGcodes.MOVE_RELATIVE, KlippyGcodes.MOVE, axis, dist, **KlippyGcodes.MOVE_ABSOLUTE**))
self._screen._ws.klippy.gcode_script(
            "%s\n%s %s%s\n**%s**" % (KlippyGcodes.MOVE_RELATIVE, KlippyGcodes.MOVE, axis, dist, **KlippyGcodes.MOVE_ABSOLUTE**)
