### ISSUE TITLE
Remaining print time is always completely of

### ISSUE THREAD

**Issue by sttts** [jordanruthe/KlipperScreen#108]
While printing the remaining time shown by Klipper screen does not match what Maintail shows. I tried with "file time" setting and "filament" setting, neither is near the Maintail values (which pretty much match the print).

Compare these photos, take within a minute. Especially, the percentage value is totally wrong.

Filament:
![IMG_2429](https://user-images.githubusercontent.com/730123/110612624-a9dc6880-8190-11eb-975d-15338446c40c.jpeg)

File:
![IMG_2430](https://user-images.githubusercontent.com/730123/110612636-acd75900-8190-11eb-8ec5-80ae39bf383a.jpeg)

Maintail:
![IMG_2431](https://user-images.githubusercontent.com/730123/110612666-b2cd3a00-8190-11eb-9457-3cb3c6701c69.jpeg)

**Comment by jordanruthe** [comment]
I'll look into this, but it should be using the same logic

**Comment by sttts** [comment]
Also note that the shown print is sometimes wrong, i.e. it shows an old preview picture. Maybe it mixes up old and new state?

**Comment by sttts** [comment]
I think it is what I wrote in the previous comment, there is overlapping state between current and old print. Compare the following screenshot. It is while heating up for a new print, i.e. like a minute into the print, not 34min.

![IMG_2454](https://user-images.githubusercontent.com/730123/111025241-1cdd1d80-83e3-11eb-8562-de22f8c31cec.jpg)

**Comment by alexcroce** [comment]
Also for me, the remaining time is a lot more than what fluidd says.

**Comment by matthewlloyd** [comment]
Another example, Fluidd is accurate here:

![DFEEACB7-28F1-4A5A-9548-F694FC448A87](https://user-images.githubusercontent.com/2041996/118741317-ff319780-b81b-11eb-9e70-5b6437223d43.jpeg)
![68563811-85CA-4D51-9625-9BCB26C9324F](https://user-images.githubusercontent.com/2041996/118741319-ff319780-b81b-11eb-8cdb-a83ef55e7574.jpeg)

**Comment by jordanruthe** [comment]
> Another example, Fluidd is accurate here:
> 
> ![DFEEACB7-28F1-4A5A-9548-F694FC448A87](https://user-images.githubusercontent.com/2041996/118741317-ff319780-b81b-11eb-9e70-5b6437223d43.jpeg)
> ![68563811-85CA-4D51-9625-9BCB26C9324F](https://user-images.githubusercontent.com/2041996/118741319-ff319780-b81b-11eb-8cdb-a83ef55e7574.jpeg)

Can you attach you KlipperScreen.log file?

**Comment by matthewlloyd** [comment]
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/6505187/KlipperScreen.log)

I have no KlipperScreen.conf so it's using defaults - file progress mode I think.

Roughly contemporaneous with the above photos:

```
2021-05-18 21:02:58,098 [screen.py:_websocket_callback()] - [
  "notify_gcode_response",
  "SD printing byte 12738412/17727772"
]
```

**Comment by b14ckw1d0w** [comment]
This may be closed but the issue remains. I have the same issue with Mainsail currently showing 78% and KlipperScreen showing 67%. I have found another recent user on Reddit with the same issue. Something is not right somewhere with the logic.

**Comment by alfrix** [comment]
Currently klipperscreen will not match the other interfaces since the percentage is calculated via estimated time, so totalPritnTime - remainingTime, it's not a bug it's intentional

**Comment by alfrix** [comment]
Let's compare to current webui percentage:
90% of the web UI means 90 of the gcode

**Comment by thearduinoguy** [comment]
As of 2nd March 2025 this issue persists.

**Comment by 0xUnkn0wN** [comment]
> Let's compare to current webui percentage:
> 
> 90% of the web UI means 90% of the gcode file done
> 
> If you completed 3 hours of a 4 hours print, would you say that is 90%?
> 
> Ks will show you 75%

That seems a bit awkward, time estimation is never 100 % correct and would fluctuate mid-print, so if i'm not wrong the percentage could go down as an example while printing because of the estimation goes up.
It would jump based on the current speed and acceleration as well.

With executed lines of gcode this could not happen, because we always know how many lines of gcode needs to be executed and how many already were executed.
