### ISSUE TITLE
[Enhancement]

### ISSUE THREAD

**Issue by robvoi** [jordanruthe/KlipperScreen#109]
Would be great if [screws_tilt_adjust] is supported.
Just a button to start it. And then show the results. (or just an ongoing console log, filtered for temp and such)

**Comment by jordanruthe** [comment]
Screws tilt adjust is currently supported. It's in the bed level panel: https://github.com/jordanruthe/KlipperScreen/blob/master/docs/panels.md#bed-level

**Comment by robvoi** [comment]
Ah, ok. Thought this is just for manual bed level without probe. (that's what I used it for)
Have to test if/how this works.

**Comment by robvoi** [comment]
soo cool, didn't see it - thanks for this great software
