### ISSUE TITLE
Requested speed on Print Status

### ISSUE THREAD

**Issue by RedGuilhas** [jordanruthe/KlipperScreen#118]
Hello.

Is it possible to show the requested speed in the Print Status panel?

Thanks

**Comment by zztopper** [comment]
Yes, I've done that in PR #151. Now waiting for checking and merging into master.

**Comment by hapklaar** [comment]
Was also looking for this info on the job status screen. It seems the changes @zztopper referred to were never merged and reverted in his own fork. Did it not work out?
