### ISSUE TITLE
Job status panel not showing gcode preview

### ISSUE THREAD

**Issue by kylix34** [jordanruthe/KlipperScreen#125]
Hi,

i installed MainsailOS with Klipper and I noticed the Job Status panel is not showing the gcode 3D model preview. It shows instead an .STL file icon.

**Comment by kylix34** [comment]
Just noticed there's another opened issue with the same problem

**Comment by TehProgrammer** [comment]
Please link the issue.  I'm also having this problem.

**Comment by Tahutipai** [comment]
Same here.  

How does KlipperScreen find the STL file?

**Comment by Tahutipai** [comment]
For anyone else looking...

In order to view the ".stl" on the screen, a thumbnail must be generated by your [slicer.
](https://docs.fluidd.xyz/features/thumbnails)

**Comment by Deluxa** [comment]
maybe it will help someone else, I was solving the same problem.....
For Cura..
1. install plugin for Cura https://github.com/emtrax-ltd/Cura2MoonrakerPlugin
2. configure your Moonraker 3D printer in Cura..... Settings -> Printer -> Manage Printers -> Connect Moonraker
3. 
<img width="548" alt="screen" src="https://user-images.githubusercontent.com/19547555/205349818-fdd8463a-7ea8-41e9-ae6d-cb66c4a28392.png">
4.slice and select "upload to (your printer)"
