### ISSUE TITLE
Change Panel infos

### ISSUE THREAD

**Issue by alexcroce** [jordanruthe/KlipperScreen#134]
Is it possibile to configure infos shown on a panel? I.e. if i want to show layers remaining in jobs panel, is it possible?

**Comment by jordanruthe** [comment]
Currently, it's not possible. But this brings up a larger discussion I was looking at having. 

I'm not happy with all the information on the jobs panel and am looking to redesign it a bit. For instance, I don't believe the X/Y positions provide much value and will likely not display them going forward. 

I'm open to suggestions here, and I may try to figure a way to have selectable info for this panel, but I'm unsure of what that'd look like right now.

**Comment by mpalm0508** [comment]
I agree with X/Y position.  I would like to see M117 messages if possible.  I have my slicers adding the current layer to a M117 message and it shows great in Fluidd.  Current speed might be good as well.

**Comment by ohjay93** [comment]
I second the idea of M117 messages, that makes it easy for me as an end-user to change what the screen shows.
Other input: X/Y values are usefull when I am setting up home position, working on probe positions etc.
Layer height is reeeeeally useful for watching for filament change positions as well as for continueing failed prints :-)

**Comment by zztopper** [comment]
Just made a PR #150 that adds a line to JobStatus panel with M117 contents, if you're still interested @ohjay93 @mpalm0508

**Comment by alexcroce** [comment]
It looks great! Thank you!
