### ISSUE TITLE
Question about screen rotation

### ISSUE THREAD

**Issue by Terixxx** [jordanruthe/KlipperScreen#135]
Hello,

I need to rotate my screen with 180 degrees. Is there any configuration parameter that can be edited for this?
Thanks in advance!

**Comment by jordanruthe** [comment]
I can add something into the docs on how to rotate a raspberry pi screen (it's done at the os level). For now, feel free to use this article: https://www.circuitbasics.com/raspberry-pi-touchscreen-calibration-screen-rotation/

**Comment by Terixxx** [comment]
Thank you very much for this help!
