### ISSUE TITLE
Bed Level Tool Displaying One Corner

### ISSUE THREAD

**Issue by rtran1995** [jordanruthe/KlipperScreen#138]
Bed leveling tool used to show all 3 corners and how much to rotate by, now I'm only able to see the back right after the most recent update. 
![image](https://user-images.githubusercontent.com/9065731/115924907-f977aa80-a445-11eb-8f56-67fdb94789ff.png)
![image](https://user-images.githubusercontent.com/9065731/115924925-02687c00-a446-11eb-924e-4f80015a480a.png)

**Comment by rtran1995** [comment]
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/6371490/KlipperScreen.log)

Bed leveling starts at `2021-04-25 02:38:17,188 [screen.py:_load_panel()] - Loading panel: bed_level`

**Comment by jordanruthe** [comment]
I was not accounting for a situation of screws with a negative position value. I just pushed a change which should address and fix your issue.

**Comment by rtran1995** [comment]
![image](https://user-images.githubusercontent.com/9065731/116139328-85364480-a69b-11eb-9a2c-d5211b6f9c60.png)
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/6379741/KlipperScreen.log)
Fixed the bottom right and back right but back left still seems to be having issues.

Screw positions remain the same.

**Comment by jordanruthe** [comment]
I missed a regex statement, let me know if this fixes the last screw for you.

**Comment by rtran1995** [comment]
Confirmed fixes issues. Thank you very much!
