### ISSUE TITLE
Add "Wi-Fi Config" button.

### ISSUE THREAD

**Issue by denziko76** [jordanruthe/KlipperScreen#141]
Good day! 
Please add a very useful "Wi-Fi Config" button.
So that you can scan and connect to any network without any problems. Imagine how convenient it will be when you move the printer to another place to connect to the network simply through the screen. No need to disassemble the printer or whatever.
Thank you for understanding.

**Comment by jordanruthe** [comment]
Hey, I am currently working on this feature.

**Comment by jordanruthe** [comment]
This has now been implemented

**Comment by Tux0Topo** [comment]
Hi there! Sorry to necropost, but ive tried with Raspberry OS x86 and it only shows the current wifi connection. In the desktop, all of them are shown. Any ideas?
It was all installed by kiauh. Thanks!
