### ISSUE TITLE
Screen Not updating.

### ISSUE THREAD

**Issue by mninja79** [jordanruthe/KlipperScreen#15]
With the latest update the screen does not update when I start a print. I have to restart KlipperScreen for it to work.

**Comment by jordanruthe** [comment]
I've pushed some updates to increase the log file verbosity. Can you please try running it again and attach your log file output from /tmp/KlipperScreen.log ?

**Comment by mninja79** [comment]
Looks like it is working now. I have attached the log file.[
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/5545780/KlipperScreen.log)
](url)

Thanks for the qick fix
