### ISSUE TITLE
Thumbnails of new files not available

### ISSUE THREAD

**Issue by kmarty** [jordanruthe/KlipperScreen#154]
Hi,
Since commit 96d252ba3cb99a06a55d9588e38a4457783c0488 any uploaded file for print which doesn't exists previously has no thumbnail when printing starts ("STL" icon is shown instead).
After searching why, it seems files are scanned only when KlipperScreen starts (in _init_printer()_)

This "hotfix" works for me (I don't say this is the right way - I simply don't know):
```diff
diff --git a/screen.py b/screen.py
index 0e49d44..8a1e116 100644
--- a/screen.py
+++ b/screen.py
@@ -689,6 +689,7 @@ class KlipperScreen(Gtk.Window):
             del self.panels["job_status"]
 
     def printer_printing(self):
+        self.files.refresh_files()
         self.close_popup_message()
         self.show_panel('job_status',"job_status", "Print Status", 2)
 
```

**Comment by jordanruthe** [comment]
Appreciate the feedback. This will be a temporary problem. Moonraker will shortly be implementing inotify which will remedy this problem. I may push something in the meantime depending on how long that will take

**Comment by jordanruthe** [comment]
Here's the pr: https://github.com/Arksine/moonraker/pull/159

**Comment by kmarty** [comment]
Oh, I see. ok.

**Comment by jordanruthe** [comment]
Arksine is planning on merging the mentioned PR Tuesday around 7:30pm EDT (UTC-23:00)

**Comment by jordanruthe** [comment]
This should be fixed. Please let me know if you're still having issues.

**Comment by kmarty** [comment]
Seems it works.
