### ISSUE TITLE
Autoreload KlipperScreen after a theme change was chosen

### ISSUE THREAD

**Issue by nicedevil007** [jordanruthe/KlipperScreen#157]
heya @alfrix,

maybe it is just for my installation but I guess not. After changing to your new addition to KipperScreen I had to restart KlipperScreen to get it working.

Maybe that can be done automatically if anyone will change this setting?

**Comment by alfrix** [comment]
maybe a dialog saying "Restart required, do you want to restart now?" or maybe just restart it's only the gui, it shouldn't affect the print

**Comment by nicedevil007** [comment]
Yeah that's what I mean, you can do it during a print, because KlipperScreen isn't affecting the print during a restart of its service.
