### ISSUE TITLE
Show & control temperature_fan data

### ISSUE THREAD

**Issue by grigi** [jordanruthe/KlipperScreen#158]
Hi, a `[temperature_fan]` section currently doesn't show up in KlipperScreen, whereas it has parameters similar to a regular heater.
It reports a temperature, and can have a "target" temperature set.

I'm currently using it in a `[temperature_fan chamber]` section to limit temperatures inside the chamber to safe values.

Could you please add support for it?

**Comment by jalderman9** [comment]
I have two temperature_fan entries and would love to see this added!

**Comment by Undefining** [comment]
I have a temperature_fan entry for my chamber. I too would like to see this added.
