### ISSUE TITLE
FR: Update all Stuff from moonraker that we can normaly update through the WebUI

### ISSUE THREAD

**Issue by nicedevil007** [jordanruthe/KlipperScreen#162]
Heya I guess everybody knows what I mean right?

Adding a button to just update the stuff from these parts would be awesome:

![image](https://user-images.githubusercontent.com/17103076/118847741-5abc5d80-b8ce-11eb-8661-f8f7d8a2da11.png)

**Comment by jordanruthe** [comment]
Closing this since update manager capability has been merged
