### ISSUE TITLE
[FR] Gcode preheat function and custom preheat presets

### ISSUE THREAD

**Issue by davide-molino** [jordanruthe/KlipperScreen#170]
Hi, I have two suggestion: the first one is custom preheat setting, if I go to the config and change the value or name it returns to default everytime I update and th moonraker updater says that the installation is invalid. The second suggestion is to add a preheat function relative to gcode in the print menu, just like fluidd does.

**Comment by jordanruthe** [comment]
You should be making config modifications to a separate file, ~/KlipperScreen.conf. That will solve issue number 1

**Comment by davide-molino** [comment]
I already make modification to that file, but fluidd updater say that is invalid. and after any update the file return to the defaults

**Comment by jordanruthe** [comment]
You shouldn't be modifying a file... If you're making changes to ks_includes/KlipperScreen.conf, it will complain about it being invalid. You have to make a new file in your home directory with that name

**Comment by davide-molino** [comment]
thank you very much. Now it works... but think about a gcode preheat please... it will be very useful
