### ISSUE TITLE
Klipperscreen won't connect to Klipper

### ISSUE THREAD

**Issue by seacred** [jordanruthe/KlipperScreen#173]
Hi there,
After the last Update to the newest Klipper-version klipperscreen seems like not connecting anymore.
Somebody else got this issue?
Thanks in advance!
Best regards

**Comment by Potplanty** [comment]
Yep, on two machines.

**Comment by jordanruthe** [comment]
Can you guys upload a log file?

**Comment by Potplanty** [comment]
> Can you guys upload a log file?

Sure thing. Before I saw this I performed a full removal of the KlipperScreen folder and cloned it again from the Github repo. Ran the installer which went through without issues. Did a full reboot of the Pi after install and it now shows another message about missing resources. Log file attached as well.
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/6604360/KlipperScreen.log)

**Comment by jordanruthe** [comment]
@Potplanty In your case, an image was renamed and wasn't able to be found. I just pushed an update that will gracefully fail/continue in this case.

**Comment by jordanruthe** [comment]
@alfrix You may want to update the icon on the solarized image.

**Comment by Potplanty** [comment]
> 
> 
> @Potplanty In your case, an image was renamed and wasn't able to be found. I just pushed an update that will gracefully fail/continue in this case.

Thanks Jordan. Working fine now.

**Comment by jordanruthe** [comment]
@seacred Are you still having this issue?

**Comment by seacred** [comment]
Works great again.
Thanks for that.
Issue can be closed.
