### ISSUE TITLE
KlipperScreen don't connect to Wi-Fi

### ISSUE THREAD

**Issue by AndrezinhoCosta** [jordanruthe/KlipperScreen#182]
Hi... 
5 ou 6 times I have installed the Octoprint with VCoreOS and when install KlipperScreen with PiTFT50 and reboot th Raspberry, I loose the wifi connection. I don't know what to do!
It shows:
"Unable to load panel network.
Check /tmp/KlipperScreen.log for more information.
Please submit an issue on Github for help."
But I can't access Raspberry by Terminal.

**Comment by jordanruthe** [comment]
How are you setting up the wireless connection? are you changing wifi settings within KlipperScreen? It's hard for me to debug this without the KlipperScreen.log file, but I understand you can't necessarily get it without a wifi connection. Do you have the ability to plug the pi in via an ethernet cable after the error occurs so you can grab the log file?

**Comment by AndrezinhoCosta** [comment]
I'm modifying the vcoreos-wpa-supplicant.txt with my Wi-Fi network and password normally. I have 4 Rasps working here with Octoprint and Logi C920e webcams.
I'm working to put this V-Core 3 assembling in my Youtube channel. But I'll close the printer and want to put the PiTFT50 on the front door with KlipperScreen.
I got a ethernet cable here! I'll try to see if I get connect to see the KlipperScreen.log.
In the boot screen it shows "Disabling power management for wlan0". I don't know if it helps...



André Luiz L. Costa
Facebook: Andrezinho Costa<https://www.facebook.com/Andrezinho.costahttp://>
Celular / WhatsApp: (021) 9-7117-1735
Banda Alma de Vinyl
________________________________
De: jordanruthe ***@***.***>
Enviado: segunda-feira, 7 de junho de 2021 22:19
Para: jordanruthe/KlipperScreen ***@***.***>
Cc: AndrezinhoCosta ***@***.***>; Author ***@***.***>
Assunto: Re: [jordanruthe/KlipperScreen] KlipperScreen don't connect to Wi-Fi (#182)


How are you setting up the wireless connection? are you changing wifi settings within KlipperScreen? It's hard for me to debug this without the KlipperScreen.log file, but I understand you can't necessarily get it without a wifi connection. Do you have the ability to plug the pi in via an ethernet cable after the error occurs so you can grab the log file?

**Comment by AndrezinhoCosta** [comment]
I just made a fresh resinstall of VCoreOS here **WITHOUT** the KlipperScreen and got the same problem. 
So, it's not a KlipperScreen problem. 
I'll look for another solution... or get crazy trying! :)

**Comment by jordanruthe** [comment]
Good luck!
