### ISSUE TITLE
After completing a z-offset adjustment the ACCEPT button does not return to parent panel

### ISSUE THREAD

**Issue by michelluccote** [jordanruthe/KlipperScreen#19]
When selecting the Accept button in the z-offset panel it seems to accept the new offset looking at the log but it does not return to the parent panel.

Looked at the source code and noticed the Abort has the _menu_go_back call but accept does not. With-out this I have no way to go back unless I press the Abort button which does not make sense. Also you stay in the z-offset UI which is not not functional because the z-offset command has ended after klipper got the Accept command.

**Comment by jordanruthe** [comment]
Just pushed an update to fix this.
