### ISSUE TITLE
Job_status getting out of screen

### ISSUE THREAD

**Issue by alfrix** [jordanruthe/KlipperScreen#190]
![2021-06-23-044419_480x320_scrot](https://user-images.githubusercontent.com/1247237/123189606-80f88e80-d474-11eb-8ff1-ee4b462ade43.png)
possible fixes:
remove label
move total time to another row
remove total time (there is elapsed and remaining)
move the status text to the left reducing the thumbnail space

**Comment by alfrix** [comment]
with the new PR
![2021-06-24-210735_480x320_scrot](https://user-images.githubusercontent.com/1247237/123349922-4bb17680-d530-11eb-8d6e-e73a2e75c1bb.png)

**Comment by jordanruthe** [comment]
Just merged this PR
