### ISSUE TITLE
Z-height with babystepping

### ISSUE THREAD

**Issue by einencool** [jordanruthe/KlipperScreen#197]
Hello, 
I've installed Klipperscreen a few days ago and fit the most things for my needs, but one thing I can't find.

In the Display while printing, it seems to show the Z-height from the G-Code. 
But when applying the Babystepping, it still shows the same values.
Is it possible, that it could show the "real current values" instead the "theoretically values"?

**Comment by alfrix** [comment]
this was fixed with ffaad4daf7b6dc2866151912bebec071c44d6cbd
