### ISSUE TITLE
Adding authentication causes the UI to fail

### ISSUE THREAD

**Issue by Shine6Z** [jordanruthe/KlipperScreen#199]
I added the authenticated user to Fluidd on the Web side, and then my KlipperScreen was stuck on the Connecting To Printer page.

**Comment by henkyprayoga** [comment]
Please check https://github.com/jordanruthe/KlipperScreen/pull/204

You should specify moonraker_api_key in KlipperScreen configuration file. However, without my patch, KlipperScreen ignoring that configuration value.

**Comment by jordanruthe** [comment]
@Shine6Z Does the merge of #204 fix the problem for you?

**Comment by chabad360** [comment]
It didn't solve it for me...
