### ISSUE TITLE
Can't access to  multiple extruder on klipperscreen 

### ISSUE THREAD

**Issue by binarylefmart** [jordanruthe/KlipperScreen#211]
Hi,
I have a multicolor 3d printer, i can access to each extruder on gui Web interface but not in klipperscreen.
Have you a fix for this issue ?

Thx guy's

**Comment by jordanruthe** [comment]
KlipperScreen can handle multiple extruders. If you are having issues, please post your KlipperScreen.log file (located in /tmp/).

**Comment by binarylefmart** [comment]
So why canot access it ? Need to modif klipperscreen.conf ?

**Comment by jordanruthe** [comment]
You must post your KlipperScreen.log file for me to be able to help you.

**Comment by jordanruthe** [comment]
If you're still having this issue, please re-open and post your log file.
