### ISSUE TITLE
Unable to successfully install KlipperScreen

### ISSUE THREAD

**Issue by hapklaar** [jordanruthe/KlipperScreen#212]
During installation on Pi4 with raspbian I get the following:

![image](https://user-images.githubusercontent.com/7703320/126903589-05151692-51bf-4902-8ae3-e04a7312696d.png)

- I'm unable to start KlipperScreen. 
- no /tmp/KlipperScreen.log exists yet
- `sudo journalctl -xe -u KlipperScreen` gives
![image](https://user-images.githubusercontent.com/7703320/126903644-f22ed804-eaeb-4263-86a9-93b227ccd994.png)
- /etc/X11/Xwrapper.conf has entry `allowed_users=anybody`
- when I do a `cat /etc/group | grep tty` I see my username

Any clue what might be wrong?

**Comment by hapklaar** [comment]
I did get it to work, but had to do some additional configuration that was not specified in the installation instructions:

- group had to be able to read from /dev/tty2 apparently >> `sudo chmod g+r /dev/tty2'
- my account had to be member of the video group as well >> `sudo usermod -a -G video $USER`

after this I was able to start with `sudo systemctl start KlipperScreen.service`

**Comment by hapklaar** [comment]
To get touchscreen to work, I had to make another permission change:
`sudo chmod o+rw /dev/input/*`

**Comment by jeffreynichols** [comment]
Thanks! that helped me finish my installation.

**Comment by LoganFraser** [comment]
I'm getting the same error, and while I can start it manually now with 'sudo systemctl start KlipperScreen.service' after a restart I get a login prompt and the error if I run a 'sudo journalctl -xe -u KlipperScreen' again.
