### ISSUE TITLE
Feature Request: Put User Selected Macros on Main Page

### ISSUE THREAD

**Issue by jallen810** [jordanruthe/KlipperScreen#216]
New (Former PanelDue) user here, great setup, really digging the UI but there is one feature I reeaaaaallly miss. Im running a bunch of macro's (Load/Unload Filament, QGL, etc.) and I would very much like to be able to just click them from the main screen without clicking thru a bunch of menus. I mocked up what I would like to see in the attached photo

![main_panel_MarkedUp](https://user-images.githubusercontent.com/62486440/127257576-4da244b0-c7d4-44cf-a524-8a7c203c789e.png)

**Comment by jordanruthe** [comment]
We've integrated a macros shortcut.
