### ISSUE TITLE
Disable screensaver on new print job start

### ISSUE THREAD

**Issue by Gi7mo** [jordanruthe/KlipperScreen#218]
I have my printer always on, so the screensaver can be enabled when i start a new print.
I would find it awesome when the screen wakes up when the new job starts.

**Comment by hawkeyexp** [comment]
good idea!

**Comment by grigi** [comment]
I was actually hoping for some kind of instruction we could send to force screen wake at print end.
Then I can add this into my print start/end macros and ensure the screen is on at those times.

**Comment by Gi7mo** [comment]
awesome, thanks for implementing
