### ISSUE TITLE
Print time estimate is behaving very strange...

### ISSUE THREAD

**Issue by hapklaar** [jordanruthe/KlipperScreen#222]
Whenever I start a print, the time-left estimate is way off. It starts ok-ish with time-left estimate close to what's expected and what Fluidd is showing. 

But then it starts to climb very rapidly. It's not uncommon for a small print, taking around 30 minutes, to show 200+hours on the estimate after a minute of printing.

After a while this way too high estimate starts dropping and returns back to a normal value.

**Comment by phil2sat** [comment]
have this behavior too, wouldnt it be possible to implement same algo as fluidd does, i mean klipperscreen has same data as fluidd has

**Comment by ichbaum** [comment]
After 30min I'm still way of.
>5h on the screen and an Estimate of 3:10 on the web interface.

**Comment by alfrix** [comment]
Closed as duplicated of #108
