### ISSUE TITLE
ERROR - Fatal error in main loop (module 'websocket' has no attribute 'WebSocketApp')

### ISSUE THREAD

**Issue by fex42** [jordanruthe/KlipperScreen#23]
After doing a completely fresh install of Raspberry Pi OS, Klipper, Moonraker, Fluidd and KlipperScreen (using KIAUH), I have everything working except KlipperScreen which throws the following error in /tmp/KlipperScreen.log:

```
2020-12-01 16:43:10,120 - KlipperScreen - ERROR - Fatal error in main loop
Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 465, in <module>
    main()
  File "/home/pi/KlipperScreen/screen.py", line 457, in main
    win = KlipperScreen()
  File "/home/pi/KlipperScreen/screen.py", line 104, in __init__
    self._ws.connect()
  File "/home/pi/KlipperScreen/ks_includes/KlippyWebsocket.py", line 61, in connect
    self.ws = websocket.WebSocketApp(self.ws_url,
AttributeError: module 'websocket' has no attribute 'WebSocketApp'
```

**Comment by JohannesBertens** [comment]
Same here.

**Comment by JohannesBertens** [comment]
I went into the Python virtual environment, removed the 'websocket' and 'websocket-client' package and did a reinstall of the requirements:

```
pi@klippi:~ $ source ~/.KlipperScreen-env/bin/activate
(.KlipperScreen-env) pi@klippi:~ $ pip uninstall websocket
(.KlipperScreen-env) pi@klippi:~ $ pip uninstall websocket-client
(.KlipperScreen-env) pi@klippi:~ $ pip install -r ~/KlipperScreen/scripts/KlipperScreen-requirements.txt
```

**Comment by fex42** [comment]
Sadly the fix of @JohannesBertens doesn't work for me. I tried it (and some variants) without success :-(

**Comment by JohannesBertens** [comment]
Oh, I forgot to mention - also removed the line with just 'websocket' in the KlipperScreen-requirements.txt file before executing the above commands, mine now looks like this:

```
requests==2.25.0
vext==0.7.4
websocket-client==0.57.0
humanize==3.1.0
jinja2==2.11.2
```

**Comment by fex42** [comment]
Ok, that worked. Had to remove the websocket line. Thank you!

**Comment by jordanruthe** [comment]
Thanks for reporting this. I just updated the requirements file per the feedback.
