### ISSUE TITLE
KlipperScreen Update Manager not disabling entire Klipper Update Manager 

### ISSUE THREAD

**Issue by jallen810** [jordanruthe/KlipperScreen#243]
Hello,

The issue I am having is that when I installed my KlipperScreen and used the Moonraker.conf specified on the documentation pages it throws this error and it removes the entire update manager section on the Klipper Dashboard. See pictures attached.
The only special detail I think to be relevant is that I am running Mainsail in Beta mode, but I have tried downgrading to stable mainsail and the issue persists.
Any advice or suggestions would be appreciated. I would like to be able to update my KlipperScreen :) 

![079FEDEF-F2C9-468F-9D82-B300FCFBE39B](https://user-images.githubusercontent.com/62486440/131053148-41623778-5ef5-4306-bf61-0bb3f102e296.png)
![E369DB89-A8DB-4632-9879-D40197648250](https://user-images.githubusercontent.com/62486440/131053152-fd57e265-865e-486f-b851-61fa4ad2e42f.jpeg)

**Comment by alfrix** [comment]
not able to replicate, everything works with the shown configuration, try updating manually and provide a the logs if it persists

**Comment by jallen810** [comment]
Resolved by uninstalling & reinstalling Klipper, Mainsail, & Moonraker.
