### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by Kirottu** [jordanruthe/KlipperScreen#253]
Is there any possibility to run this software on an android device? I recently made a casing for this old tablet to use for controlling this printer, but the web interface for fluidd is not very responsive or fast on that very old tablet. This project seems like an ideal option if it would support android.

**Comment by jordanruthe** [comment]
This project won't provide official android support, you'll have to do that on your own if you want it.

That said, users in the klipper discord have installed vnc (via a scraping server) and used a VNC Viewer application on android to display KlipperScreen over an android tablet.
