### ISSUE TITLE
missing logo/symbol in different screens

### ISSUE THREAD

**Issue by Fr33man85** [jordanruthe/KlipperScreen#254]
Hi,

there are missing symbols in some screens. 
It shows a small box with "21 91" instead. 

i think, this should be some arrows. I can provide some pictures later.

greetings
Manuel

**Comment by Fr33man85** [comment]
Hi, 
yes, sry, i forgott to send some. I do today after work.

**Comment by alfrix** [comment]
interesting, for some reason your font doesn't have the glyphs "↑" "↓"
a possible fix would be to draw svg images with arrow up and arrow down (these already exist in the themes)

Fr33man85 does the "→" show up while heating the extrude or bed?
as in "50 → 210ºC"

**Comment by Fr33man85** [comment]
I dont have a screen, where are horizontal arrows. Not on screen "Preheat", not on the print screen:

![20210909_170442_1024x1024_500KB](https://user-images.githubusercontent.com/50385199/132711735-0222a2b2-a9a1-457d-911e-aa4c955d4f6d.jpg)

**Comment by Fr33man85** [comment]
Hey Alfrix,
now i know what you mean and yes, same issue with the "->" arrows

**Comment by jordanruthe** [comment]
@Fr33man85 Can you check to see if this update fixes it? The package is `fonts-freefont-ttf`

**Comment by Fr33man85** [comment]
@jordanruthe solved! thanks
