### ISSUE TITLE
Job status panel doesn't show up if print is started from Octoprint

### ISSUE THREAD

**Issue by dodgeboy** [jordanruthe/KlipperScreen#256]
My job status panel shows up fine if I start the job from the KlipperScreen.  But if I start the job from OctoPrint, the KlipperScreen just stays at the main menu for the entire print.  I've searched everywhere and I can't find a config or gcode trigger that I am missing that would tell KlipperScreen a print has started.

[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/7121791/KlipperScreen.log)

**Comment by alfrix** [comment]
Octoprint it's not native, it send commands to klipper, for that reason use Octoscreen or Octodash or something that connects to Octoprint instead

**Comment by dodgeboy** [comment]
> Octoprint it's not native, it send commands to klipper, for that reason use Octoscreen or Octodash or something that connects to Octoprint instead

Thank you for your reply.  Does that mean there is no way to trigger klipperscreen to show the job status if the job starts with Octoprint?  I would really prefer to run klipperscreen, because of how tightly it integrates with klipper.  The screen updates basically instantaneously.

**Comment by alfrix** [comment]
> because of how tightly it integrates with klipper. The screen updates basically instantaneously.

if you want speed and integration, use Mainsail or Fluidd along with KlipperScreen

**Comment by dodgeboy** [comment]
I definitely will once it supports the spaghetti detective.
