### ISSUE TITLE
Display nozzle temperature in extrusion panel

### ISSUE THREAD

**Issue by michelluccote** [jordanruthe/KlipperScreen#27]
I was using the extrusion panel and tried to extrude while the nozzle was still warming up. I can see the temp control option on this panel but it would be very useful to see the current temperature in the extrusion panel. In my case I had already set the temp and just had to wait for it to reach this target temp. Having it displayed would save me having to go to the sub panel or another panel to see the current temp.

**Comment by jordanruthe** [comment]
The temp should be displayed in the extrude panel, I just pushed a fix to enable it.

**Comment by michelluccote** [comment]
Excellent. Your so fast I have to update KlipperScreen between every print! I'll get it updated tomorrow after my 24hr print.
