### ISSUE TITLE
No working panel limits

### ISSUE THREAD

**Issue by ShohninDmitriy** [jordanruthe/KlipperScreen#272]
No working panel limits
![20210917_134618 (2)](https://user-images.githubusercontent.com/20542738/133771055-11ec406c-3802-4bbc-bbbd-d1c8b6806811.jpg)
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/7185025/KlipperScreen.log)

**Comment by hawkeyexp** [comment]
Check your square_corner_velocity in section [printer] - i had the same issue and the logs told me that the panel is awaiting an integer but my value was 5.0 which is a float - change 5.0 to 5 for example - if it's not the reason check the log in /tmp/KlipperScreen.log for addditional errors.

**Comment by ShohninDmitriy** [comment]
> 
> 
> Check your square_corner_velocity in section [printer] - i had the same issue and the logs told me that the panel is awaiting an integer but my value was 5.0 which is a float - change 5.0 to 5 for example - if it's not the reason check the log in /tmp/KlipperScreen.log for addditional errors.

Thank you, everything worked.
