### ISSUE TITLE
Bed_level: screws tilt adjust doesn't update the values after running the tool

### ISSUE THREAD

**Issue by alfrix** [jordanruthe/KlipperScreen#275]
![imagen](https://user-images.githubusercontent.com/1247237/133844690-927be522-ad33-4ca9-a271-1c827707bec0.png)

**Comment by alfrix** [comment]
the problem was introduced with 54c47554d2c8ed1de086bda00fdd209cac28cdd2
if i revert, it works
![imagen](https://user-images.githubusercontent.com/1247237/133845588-062a571c-ac83-42be-b9bf-bf12a93e3931.png)

**Comment by Pr20100** [comment]
Hello, same here, the values are not updated if I run the tool on the screen for a second run (but correct in the console).
Runing v0.1.6-102-gd7b8f4f

@alfrix : What do you understand by "revert"? (order of probed points?)

**Comment by jordanruthe** [comment]
@alfrix @Pr20100 I believe I fixed this, can you please confirm that it's fixed?

**Comment by Pr20100** [comment]
@jordanruthe Yes it's fixed, thanks a lot!
