### ISSUE TITLE
No preview in the printing dialogue. 

### ISSUE THREAD

**Issue by furrywall** [jordanruthe/KlipperScreen#294]
There is no preview of the gcode in the file list or the printing screen. it just displays a icon with .stl on it.

Am I missing something simple?

**Comment by jordanruthe** [comment]
You have to configure your slicer to generate thumbnails. https://docs.fluidd.xyz/features/thumbnails

**Comment by furrywall** [comment]
Thankyou so much. I was using Cura but have moved to SuperSlicer. All working now.
Sorry to bother you with such a basic issue. An hour of googling did not work :(
Have a good day.
Regards
