### ISSUE TITLE
job_status: Fan_generic speed

### ISSUE THREAD

**Issue by schuessm** [jordanruthe/KlipperScreen#303]
I see no status, fan speed of the part cooling fan, on the status screen. There is only the icon with no speed
[klippy.log](https://github.com/jordanruthe/KlipperScreen/files/7352933/klippy.log)
[moonraker.log](https://github.com/jordanruthe/KlipperScreen/files/7352934/moonraker.log)

**Comment by schuessm** [comment]
No idea?

**Comment by jordanruthe** [comment]
The fan icon on the status screen if keying off [fan] not [fan_generic] or another configuration option in Klipper
