### ISSUE TITLE
Network panel not functioning when wifi point is within range

### ISSUE THREAD

**Issue by kotovskii** [jordanruthe/KlipperScreen#304]
Hello.
If my printer is connected to network №1, and I want to relocate it to other room/building, where wifi network №1 does not work, but there is network №2, to which I want to connect printer now, I do following:
I turn off printer and relocate it, then I turn it on outside of network №1 range. Then, when trying to enter the Network panel, "Unable to load panel network" error pops up. To properly switch between networks, I need to create a hotspot on my mobile device with a name and password like wifi network №1, wait for a connection and then connect to network №2.

**Comment by vladimir-poleh** [comment]
I think this issue can be closed.
