### ISSUE TITLE
GCode Preview

### ISSUE THREAD

**Issue by aeremichev** [jordanruthe/KlipperScreen#308]
In the documentation, the pictures show that a preview of the printed model can be displayed in the interface.

https://klipperscreen.readthedocs.io/en/latest/panels/#print
https://klipperscreen.readthedocs.io/en/latest/panels/#job-status

My preview is not displayed.
Is this not yet implemented or is there something wrong with me?

**Comment by Athemis** [comment]
You need to configure your slicer to include thumbnails within the gcode. 
The process is described here: https://docs.mainsail.xyz/quicktips/thumbnails
