### ISSUE TITLE
Confirmation for emergency Stop

### ISSUE THREAD

**Issue by bixicy** [jordanruthe/KlipperScreen#321]
Hi,
can you add a popup confirmation for emergency stop? 

I unintentionally canceled a print today....

**Comment by simpat1zq** [comment]
Not just on the emergency stop, but it would be nice to prevent a reload of klipper while a print is running. Yesterday, I switched printers, and there's a screen that shows for 2 seconds that has a restart klipper button. I accidentally tapped that button and it killed the print. Especially with a touch screen, I don't think it should be that easy to end a print.
