### ISSUE TITLE
Power State isn't synced with Moonraker

### ISSUE THREAD

**Issue by nicedevil007** [jordanruthe/KlipperScreen#322]
Hey jordanruthe,

just small "thing" (I guess so).

After some time the PowerPlug is turned of by klipper during a setup timeout. On fluidd or mainsail the state of the powerplug is shown correctly then but not on KlipperScreen. Is there a way to fix this?

**Comment by nicedevil007** [comment]
sry was wrong, that is an issue from moonraker... it didn't check from time to time the right state of the Powerdevice and tho it is in wrong state after shutdown :(

**Comment by nicedevil007** [comment]
Mhhh, no it seems to be an issue on KlipperScreen Site after testing multiple times now:

State on Fluidd/Moonraker:
![image](https://user-images.githubusercontent.com/17103076/140643944-650e31da-d60c-4c17-97eb-ddafdc4d1e71.png)

And here the state on KlipperScreen:
![image](https://user-images.githubusercontent.com/17103076/140644032-a7c496aa-a590-4551-9ebb-bc003836e8fc.png)

**Comment by hawkeyexp** [comment]
i can confirm the same with my sonoff-devices which are attached and working.

**Comment by jordanruthe** [comment]
Let me know if you still have problems.

**Comment by hapklaar** [comment]
@jordanruthe The problem persists. After Fluidd switches the Tasmota device off, KlipperScreen does not pick this up and still shows it as ON. Have to switch it off, then on again to power on the printer from KlipperScreen
