### ISSUE TITLE
Require confirm on Emergency Stop

### ISSUE THREAD

**Issue by ckvsoft** [jordanruthe/KlipperScreen#341]
Hallo
Feature Request
It would be nice that this feature, Require confirm on Emergency StopShow a confirmation dialog on Emergency Stop,
 like the new Mainsail (beta) has also been included in Klipperscreen. It hasn't happened to me in the first place that I accidentally reached the icon.

lg Chris

**Comment by alfrix** [comment]
Duplicate of #321
