### ISSUE TITLE
tapping on heated bed in preheat doesn't carry over to numeric keypad

### ISSUE THREAD

**Issue by firsttest12** [jordanruthe/KlipperScreen#351]
In Preheat submenu, if you tap on the heated bed (on a printer with nozzle, heated bed...) it changes tone to show that it's been selected. However if you then tap on "keypad" when the keypad comes up you have to select the heated bed all over again. The selection does not carry over.

(Personally I'd like to just tap on heated bed and get the numeric keypad directly, but that's a feature request!)

**Comment by jordanruthe** [comment]
In the preheat menu, all items are selected by default. Tapping on the bed is actually unselecting it.

Preheat options are not carried over to the temperature page, as you can have multiple options selected for pre-heat while the temperature panel can only have one option selected.
