### ISSUE TITLE
[FR] More filters for multi printer usage

### ISSUE THREAD

**Issue by hawkeyexp** [jordanruthe/KlipperScreen#374]
Since a short time i use klipperscreen for 2 printers which are very different. One is a voron 2.4 one is an old anycubic i3.
It would be great to show or hide parts of the gui by selected printer - for example the bed leveling method which is different between both. Extending the filters where cureently printer.bltouch or printer.power_devices.count is available would be a great way - printer['mcu'].mcu_constants includes the type for example atmega2560 for the any i3 and lpc1768 for the voron which could be used as filter condition.

Alternativly an other custom flag which could be set to identify which printer is currently used like the name which is selectable during switrching printers which would be the clearest way.

**Comment by alfrix** [comment]
the menu should be filtered by printer capability not by name or mcu, bed leveling is now filtered in the default configuration and there are more options, to use
