### ISSUE TITLE
No Tool / nozzle temperature / coordinates

### ISSUE THREAD

**Issue by robvoi** [jordanruthe/KlipperScreen#38]
KlipperScreen shows no tool / tool temparature.
Log states: Toolcount: 0

Also the coordinates on the move panel doesn't update the coordinates.

I installed using the KIAUH script. Current KlipperScreen verison is 0.1.2-58

Any idea?

[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/5745208/KlipperScreen.log)

**Comment by jordanruthe** [comment]
Can you post your entire klipper config or the klipper config log?

**Comment by robvoi** [comment]
Thanks for looking into it!
Here fresh logs and the printer.cfg. All after a fresh reboot with no further actions.

[moonraker.log](https://github.com/jordanruthe/KlipperScreen/files/5746640/moonraker.log)
[klippy.log](https://github.com/jordanruthe/KlipperScreen/files/5746641/klippy.log)
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/5746643/KlipperScreen.log)
[printer.cfg.txt](https://github.com/jordanruthe/KlipperScreen/files/5746644/printer.cfg.txt)

**Comment by robvoi** [comment]
Small update: the main screen doesn't show the extruder. In the extrude panel I see the extruder. Also with its temperature.
There is just a very big delay (in minutes) on showing the actual values.

**Comment by jordanruthe** [comment]
Can you update and re-run? I've made some changes but also included some debugs which would help me narrow down this problem.

**Comment by robvoi** [comment]
Great that you are on it. KlipperScreen would be a great feature for my printer.
Updated and tested. No change with the new version (also not for the other issues, which may all be connected).
Fresh logs attached.

[KlipperScreen_after_klipper_restart_(now_pass_init).log](https://github.com/jordanruthe/KlipperScreen/files/5748811/KlipperScreen_after_klipper_restart_.now_pass_init.log)
[KlipperScreen_after_reboot.log](https://github.com/jordanruthe/KlipperScreen/files/5748812/KlipperScreen_after_reboot.log)

**Comment by jordanruthe** [comment]
Do you have a heated bed on your printer?

**Comment by robvoi** [comment]
Not yet installed. Can be done tomorrow though.

**Comment by jordanruthe** [comment]
I wasn't accounting for no heated bed. I just pushed another change that fixes several panels for your case.

**Comment by robvoi** [comment]
Great. This solved the issue. Same for the init problem.
So far only only the job status part #37 is left. I will update this one and close the others.

Again - thanks for the effort you put into this project.
