### ISSUE TITLE
show_cursor doesn't seem to work

### ISSUE THREAD

**Issue by luizbgomide** [jordanruthe/KlipperScreen#381]
I've tried to run Klipper on a netbook and use klipperscreen on it. The display works fine and I can see Klipper screen, but since it doesn't have a touch screen all input must be done via a touch pad or mouse.

I tried to activate the `show_cursor` setting without any luck, there is no cursor visible. Is there something else that I must do?

**Comment by alfrix** [comment]
Just tested and it's working:
```
[main]
show_cursor = True
```
Restart KlipperScreen to apply

**Comment by luizbgomide** [comment]
My mistake, I wasn't using the `[main]` section...
Thanks!
