### ISSUE TITLE
the print screen does not display the newly recorded gcode

### ISSUE THREAD

**Issue by vacapetr** [jordanruthe/KlipperScreen#4]
hi, the print screen does not show the newly uploaded gcode. The restore button on the screen does not work. The service must be restarted "sudo systemctl restart KlipperScreen.service". Additionally, the uploaded file does not match. it shows me 50 years ago.

**Comment by jordanruthe** [comment]
The print screen should be updating now. Currently, directories are not working properly, I'll be addressing that in the future.

For the file time, I removed a function that modifies it. If it is still showing an incorrect time, something is wrong with the time on your system, or it's improperly reporting from moonraker.

**Comment by vacapetr** [comment]
Hello, the newly uploaded g-code will already be displayed.
The time is still displayed incorrectly. Mainsail displays it correctly.
![Snímek z 2020-11-09 19-53-53](https://user-images.githubusercontent.com/73720287/98584237-e1f89b00-22c5-11eb-8fb2-fc84ed1e33a2.png)
![IMG_20201109_195228](https://user-images.githubusercontent.com/73720287/98585129-1a4ca900-22c7-11eb-9e47-96d8cd6c3835.jpg)

**Comment by jordanruthe** [comment]
The time should now be displayed in the format of 2020/11/09 16:38

**Comment by vacapetr** [comment]
I confirm the time ok
