### ISSUE TITLE
gcode files in subdirectory not parsing correctly

### ISSUE THREAD

**Issue by thrasherht** [jordanruthe/KlipperScreen#40]
If you create a sub-directory in `~/sdcard/` and place some gcode files in it, the gcode thumbnail as well as the estimated print time do not parse.

Also some of those files won't allow you to start the print from them.

**Comment by jordanruthe** [comment]
Can you post your KlipperScreen log file? I released a commit ~five days ago that should have fixed this.

**Comment by thrasherht** [comment]
Pulled updated code and issue is addressed.
