### ISSUE TITLE
Unable to define menu in an include file

### ISSUE THREAD

**Issue by randellhodges** [jordanruthe/KlipperScreen#408]
As soon as I try to put a `[menu __main`... inside an include file, I no longer have a main menu. If I remove it from the include and just paste it into my KlipperScreen.conf file, it works.

Maybe this is causing it to get completely deleted if it was loaded by the include a couple lines earlier?
https://github.com/jordanruthe/KlipperScreen/blob/master/ks_includes/config.py#L52-L58

**Comment by alfrix** [comment]
Closed in favor of tracking only 1 issue describing this

**Comment by alfrix** [comment]
#530
