### ISSUE TITLE
zcalibrate.py accept(): misslng final line

### ISSUE THREAD

**Issue by truckershitch** [jordanruthe/KlipperScreen#409]
After clicking **Accept** from the z calibrate panel, KlipperScreen remains there.  The `ACCEPT` command is sent to Klipper and can be seen in the console.

It looks like the last line in the accept() function is missing.  Appending the last line from the abort() function

`self.menu_return(widget)`

fixes the issue.

**Comment by TehProgrammer** [comment]
Ahh, looks to be.
I just updated today (version v0.2.0-20-g58e0aa7)

**Comment by randellhodges** [comment]
Simple fix and I was doing other stuff so I did a PR. Credit to @truckershitch for the actual hard work.
