### ISSUE TITLE
Improve Documentation For Customization

### ISSUE THREAD

**Issue by TehProgrammer** [jordanruthe/KlipperScreen#416]
I've noticed that there isn't much documented on this project, and is really one of the only things preventing wider adoption in my opinion.  

I want to easily be able to customize my display in a way that suits my purposes, but it seems intimidating to me.  

This is a wonderful project, and I want to see it become extremely popular like it deserves!

**Comment by alfrix** [comment]
a general "improve" is not a valid issue, if you want to re-write something because you can explain better, then do a PR
