### ISSUE TITLE
No Move Actions after updates

### ISSUE THREAD

**Issue by robvoi** [jordanruthe/KlipperScreen#42]
I updated Klipper, Moonraker and Klipperscreen.
Now the move actions (X+,X-,Y+ ...) don't do anything anymore. The rest seems to be fine. (homing, heating etc.)
Control via Klipperscreen works. 

Klipper 0.9.1-143
Moonraker 0.2.8-27
Mainsail 0.4.1
KlipperScreen 0.1.2-85

[moonraker_noMove.log](https://github.com/jordanruthe/KlipperScreen/files/5791380/moonraker_noMove.log)
[klippy_noMove.log](https://github.com/jordanruthe/KlipperScreen/files/5791381/klippy_noMove.log)
[KlipperScreen_noMove.log](https://github.com/jordanruthe/KlipperScreen/files/5791382/KlipperScreen_noMove.log)

**Comment by jordanruthe** [comment]
Good catch, sorry about that. Just pushed an update.

**Comment by robvoi** [comment]
Wow. Lightspeed support. Thanks a lot. This solved the problem.
