### ISSUE TITLE
No automatic refresh of temperature_fan 

### ISSUE THREAD

**Issue by Tim2309** [jordanruthe/KlipperScreen#429]
I encountered a bug with the new temperature screen.
If you set a temperature_fan to 50C and change it through the Mainsail Webinterface, Klipperscreen didn't notice the change.
On extruder and bed heater the target temperature refresh works.

**Comment by Tim2309** [comment]
The problem still exist if you use a custom gcode on the klipperscreen config to change the temperature

[preheat ABS]
# Temperature for the heated bed
bed: 110
# Temperature for the tools
extruder: 260
# Temperature for generic heaters
#heater_generic: 40
# Temperature controlled fans (temperature_fan in klipper config)
temperature_fan: 50
# optional GCode to run when the option is selected
gcode: SET_TEMPERATURE_FAN_TARGET temperature_fan=controller TARGET=30

**Comment by alfrix** [comment]
The issue was that you are setting temperature fan to 50 then changing it in the gcode to 30
the target where applied but the ui was not updated.
7db75ec should fix this
