### ISSUE TITLE
[FR] System Shutdown

### ISSUE THREAD

**Issue by robvoi** [jordanruthe/KlipperScreen#43]
Would be great to have an option to shut down the host system.
So the system can be shut down from the panel before switching of power.

I first though implementing it as a Klipper Macro. But it seems system calls are not possible as macros.

**Comment by LucidityCrash** [comment]
I came here looking for this :)

**Comment by jordanruthe** [comment]
There are now reboot/shutdown buttons in the system panel.

**Comment by LucidityCrash** [comment]
Bah ... just done this myself and was about to fork to make pull request :)

**Comment by LucidityCrash** [comment]
just to confirm, works brilliantly
