### ISSUE TITLE
Fan Speed percentage is wrong on print screen

### ISSUE THREAD

**Issue by moelski** [jordanruthe/KlipperScreen#444]
Hi !

MainSail reports a fan speed at 33% where as klipperscreen reports only 13%. 
Another sample is Mainsail 100% and KS 40%. 

I assume there is a calculation error. Since the Fan speed is set in 255 steps. 
13% * 2.55 > 33%. 

regards 
    Dominik

**Comment by randellhodges** [comment]
Which fan? With an older version of moonraker and older version of fluidd, I see 40% in both fluidd and klipperscreen.

fluidd v1.6.2
moonraker v0.7.1-63-g8676465

**Comment by alfrix** [comment]
cannot reproduce configured hotend as fan_generic to adjust, also tested as heater_fan and it works ok too
![imagen](https://user-images.githubusercontent.com/1247237/149642393-01ad6567-7caa-43eb-bae5-f68989cb0eab.png)

**Comment by moelski** [comment]
Try to reproduce it with my next prints.

**Comment by moelski** [comment]
Hi !
Just make another print and could do some testing ... 
![firefox_s3GZZ3DIVy](https://user-images.githubusercontent.com/17078960/149829181-dd1019c3-f553-42b5-a406-0a8e1a3e98a1.png)
I set the fan speed in MainSail to ~40%. In Klipperscreen I see 16% (which is 40 / 2.55). 

![firefox_Q1TRqvRk9f](https://user-images.githubusercontent.com/17078960/149829221-f83b047a-9bf6-4d2b-92e9-52dcfffdd336.png)
The correst M106 command is send ... 

`Which fan?`
It´s the part fan ... 

Versions are the latest from all components: 
klipper
v0.10.0-234-g02d5f975
KlipperScreen
v0.2.0-34-g5d3bae8
moonraker
v0.7.1-300-g5f54a23
timelapse
v0.0.1-96-g90a277c
mainsail
v2.1.0-rc1

**Comment by moelski** [comment]
Ok and just another print ... Just from the beginning ... 
![grafik](https://user-images.githubusercontent.com/17078960/149832443-7516055f-d9dd-44fa-bc2a-a2f312da3fb4.png)

MainSail schows 100% but the print screen only 40% in KS

**Comment by alfrix** [comment]
can you post the fan config?

**Comment by simonvez** [comment]
I have the same issue when I configure the  MAX_POWER  in klipper printer.cfg. For instance.. if I set max_power at 50%... when I wask 100%, it will show 50%... but mainsail will show 100%. Would be nice if klipper screen would not do that and just do like mainsail does and show the real percentage and not the calculated percentage based from what kipper max_power does.

**Comment by alfrix** [comment]
i expected it to be some config, i can reproduce this behavior now, i should be able to fix it, thank you for your help
