### ISSUE TITLE
How to change scroll behavior?

### ISSUE THREAD

**Issue by simpat1zq** [jordanruthe/KlipperScreen#466]
So I just got 3 screens for my 3 printers. Kuman 7 inch capacitive touch. It is usb and hdmi based. 1 of them are on a pi4, and the other 2 are in a Pi400. The ones on the Pi400 show up with the proper scaling, and the Pi4 looks squished vertically. However, the bigger issue is that the 2 Pi400s only scroll if I slide the scroll bar on the right. The Pi4 works as expected and allows me to swipe up and down anywhere to scroll the page up and down. Any ideas as to why this is happening? I prefer the behavior on the Pi4.

**Comment by alfrix** [comment]
> Pi400 show up with the proper scaling, and the Pi4 looks squished vertically

compare /boot/config.txt they are probably using different drivers any change in the file will need a reboot.

scroll is not configurable and should be equal, maybe i need screenshots because i don't understand what you are describing
