### ISSUE TITLE
Feature request: Operating System Reboot/poweroff Button

### ISSUE THREAD

**Issue by klHaribo** [jordanruthe/KlipperScreen#47]
Sometimes I loose network on my printer(s). but with no keyboard or mouse it would be useful to powerdown/reboot the whole system. Due to my waveshare display the GPIO-pin to reboot is not accessable to install a switch there. 
So a touch menu entry would be very nice..

**Comment by robvoi** [comment]
This one just got implemented one version back. Maybe have a look at the latest release and close the issue.

**Comment by klHaribo** [comment]
Yes, seen it too late..
