### ISSUE TITLE
[FR] - different main screen layout on bigger screens

### ISSUE THREAD

**Issue by hunagyp** [jordanruthe/KlipperScreen#48]
Hi,
First of all - Thank you for your great work for this app :)

Given the below 7" touch screen (1024x600).
0.
It would be nice, if the GUI itself could reload it's config file (either by a button which is always on the screen or if it detects when the file is changed) - it would be good for testing different menu layout modifications without restarting the service
1.
I feel the left half of the main screen is wasted with just the temperatures are sitting there.
Instead, what I would like to do:
- to be able to hide the temperature buttons or make them quite small, even move them to like a statusbar/titlebar part of the screen
- place instead (several) smaller simple, clickable buttons (just like Homing, Preheat, etc but smaller sized, customizable, with/without icon/text)
- maybe customization option for button size, position (absolute/relative on the current screen)
- connect these buttons to klipper macros / OS (linux) commands (for example, I could call a linux bash script if I would like to, not kist macro/gcode)
- to be able to define this structure in the Klipperscreen config file just like we can the current menu structure with possiblity of cusomizeable standard dialogs, like "Are you sure you want to prime the nozzle? Yes/No" and similar. Just similar your current Config Save section below:

```
[menu __main config save]
name: {{ gettext('Save Config') }}
icon: complete
method: printer.gcode.script
params: {"script":"SAVE_CONFIG"}
confirm:
    {{ gettext('Save configuration.') }}
    {{ gettext('Klipper will reboot') }}

```
 
![7_inch_htmi](https://user-images.githubusercontent.com/15072282/104235098-c3915600-5454-11eb-8ce8-27d46eec0e2a.png)

+1: If KlipperScreen is installed beside for example MainSailOS, most of the config files resides in /home/<user>/config_klipper directory. You might consider in your installation to either automatically link there your config file or make it possible during installation to select the actually used config directory.
Or if you would implement [include extra-config.cfg] logic in your config file (like klipper's config file), we could create the customization in different directory than KlipperScreen's own dir.

Thanks a lot in advance!

**Comment by alfrix** [comment]
jordan and myself have implemented most of this,  and restarting the service is not a big deal now since performance has improved a lot
