### ISSUE TITLE
Having more that 6 Temperatures

### ISSUE THREAD

**Issue by arne182** [jordanruthe/KlipperScreen#489]
When more than 6 Temps the graph is quite squashed at the bottom of the display. It would be nice to have the temperatures scrollable and the graph at least fill half of the display.

**Comment by alfrix** [comment]
i assume that you are talking about the main menu, does the temp panel look good in your configuration?

**Comment by alfrix** [comment]
fixed via 8375606

**Comment by arne182** [comment]
Works perfectly
:
![image](https://user-images.githubusercontent.com/844102/152650868-91cd3318-68f5-4f22-94f6-f57f3f3bed9a.png)

Thanks
