### ISSUE TITLE
macros visibility does not work as expected

### ISSUE THREAD

**Issue by hunagyp** [jordanruthe/KlipperScreen#49]
There are items which are selected to be hidden but are still shown.
END_PRINT, M600,PURGE_LINE_BEFORE_PRINT
And some are set to be shown but are not visible:
CANCEL_PRINT,LOAD_FILAMENT,PURGE,PARK...

My Macros screen:
![1610401516852](https://user-images.githubusercontent.com/15072282/104242757-e8d79180-545f-11eb-8fa4-e57d68dec081.jpg)

Macros visibility settings:
https://www.youtube.com/watch?v=cWiBNtBtAp4&feature=youtu.be

[KlipperScreen.conf.txt](https://github.com/jordanruthe/KlipperScreen/files/5798517/KlipperScreen.conf.txt)
[klippy (2).log.txt](https://github.com/jordanruthe/KlipperScreen/files/5798518/klippy.2.log.txt)
[KlipperScreen.log.txt](https://github.com/jordanruthe/KlipperScreen/files/5798519/KlipperScreen.log.txt)

**Comment by jordanruthe** [comment]
I've made some changes to the macro panel which should fix this problem.

**Comment by hunagyp** [comment]
@jordanruthe Thank you a lot, I tried this patch and the macros are correctly shown/hidden now 👍
