### ISSUE TITLE
[Enhancement] Webcam(Nozzle Cam) viewer

### ISSUE THREAD

**Issue by DannerD3H** [jordanruthe/KlipperScreen#494]
My printer has a rather big touch screen and a Nozzle cam. It would be really cool to be able to view this nozzle cam on the klipper screen. It is just a second webcam connected to the pi via USB. 

Is this something that would be possible?

Would be really cool not to have to use the webinterface on a different device to see the nozzle cam.

**Comment by alfrix** [comment]
Duplicate of #67
