### ISSUE TITLE
Screen goes black and won't wake

### ISSUE THREAD

**Issue by mhackney** [jordanruthe/KlipperScreen#5]
7" HDMI panel. There is no menu on it to set screen saver time so this must be happening external to it. After just a few minutes the KlipperScreen goes black and won't redisplay until I turn the panel off, on and then press on again. The first time I turn on I see the RPi log and then an "Input not Found" error, the second On press activates KlipperScreen. Is there a config somewhere to completely disable this time out?

**Comment by mhackney** [comment]
Ok, with some digging I did find a disablescreenblank.sh into scripts directory. Maybe a little documentation would help cut down the wasted time and posts? I'm happy to help with docs if time is the issue.

**Comment by jordanruthe** [comment]
The disablescreenblank.sh should have been running from the startup script. I just pushed a change to include that, but you'll have to re-run the installation script.

**Comment by mhackney** [comment]
great, thanks

**Comment by jordanruthe** [comment]
Sure. Also, feel free to contribute any documentation you would like.
