### ISSUE TITLE
I cannot get klipper screen to connect to printer

### ISSUE THREAD

**Issue by Regenerate3d** [jordanruthe/KlipperScreen#512]
Hi All,

I have looked at the logs and it shows clipper screen is trying to connect to an ip but the pi doesn't have a stand alone ip as it not on wifi etc. so the question is ive been looking at everything and i keep seeing moonraker config but I'm not using moonraker. Im using octoprint and klipper so called octoklipper. How do i configure the klipper screen to tak to klipper control board or raspberry pi4. I'm new to this so i cannot find the instrustion set in looking for to get klipper creen to work. 

Mant thanks

**Comment by alfrix** [comment]
KlipperScreen was designed to be used with moonraker, it doesn't work with octoprint and it will never be compatible, use octoscreen or octodash or something that supports octoprint.
