### ISSUE TITLE
Klipperscreen can't start up on Raspberry CM4 (Pi 4)

### ISSUE THREAD

**Issue by hadesz** [jordanruthe/KlipperScreen#537]
It doesn't matter whatever I do with config and permissions, it can't start up.

The error is: "(EE) xf86OpenConsole: Cannot open virtual console 2 (Permission denied)"
I checked the the suggestions on https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/,
pi user is in tty group, and the "allowed_users=anybody" is also present in /etc/X11/Xwrapper.conf

I assume this has sthg to do with the new graphics of the PI4...
Any ideas?

**Comment by alfrix** [comment]
have you tried installing xserver-xorg-legacy ?

**Comment by hadesz** [comment]
> have you tried installing xserver-xorg-legacy ?

that was it, thanks... maybe worth mentioning in troubleshoot page
