### ISSUE TITLE
Control output_pin

### ISSUE THREAD

**Issue by Tim2309** [jordanruthe/KlipperScreen#546]
Hello,

is there a way to control a LED like the cooling fan or nevermore with a slider?
Only way which work is to set the LED as a fan in the config but that cause wrong icons for the LEDs.

**Comment by alfrix** [comment]
is it configured as an output_pin?

**Comment by Tim2309** [comment]
Yes, the config is:

[output_pin caselight]
pin: PB5
pwm: true
value: 0.3
shutdown_value: 1.0
cycle_time: 0.001

**Comment by yzheka** [comment]
@Tim2309 But what if leds can be only on/off, no pwm?

**Comment by Tim2309** [comment]
I think most people use led strips and they are always dimable

**Comment by yzheka** [comment]
My not

**Comment by Tim2309** [comment]
A simple on/off is already integrated, but I don’t know how to use it.

**Comment by bartlammers** [comment]
> Right. On/off is working on klipper, but it is not available via klipperscreen. The only workaround is toggle macro

In your KlipperScreen.conf :
`[menu __main actions lights]
name: {{ gettext('Lights') }}
icon: light
method: printer.gcode.script
params: {"script":"_TOGGLE_CASELIGHT"}`

In your printer.cfg :
`[gcode_macro _TOGGLE_CASELIGHT]
gcode:
  SET_PIN PIN=caselight VALUE={(not printer['output_pin caselight'].value)|int}`

This works for me, but only as an on/off toggle indeed
