### ISSUE TITLE
Raspberry Pi 7" Touchscreen Display // Touch not working

### ISSUE THREAD

**Issue by nshoobridge** [jordanruthe/KlipperScreen#547]
Display is showing screen normally. Touch function is not working. Raspberry 4 with Pi 7" Touchscreen Display. Already tried GL G2 driver. No luck. Everything up to date.

**Comment by hawkeyexp** [comment]
i2c enabled ? The touch control and brightness is released this way.

**Comment by nshoobridge** [comment]
SDA and SCL Pins are currently not connected. Thought that is is not needed on PI4. Will try and provide feedback. Thanks

**Comment by hawkeyexp** [comment]
Wiring is not needed - it is also connected by the dsi cable.
Check your config.txt if the i2c interface is eabled or use raspi-config to enable i2c interface

**Comment by nshoobridge** [comment]
Any other things where i should look into?

**Comment by hawkeyexp** [comment]
Not really - if possible do a plain test - use a clean a sdcard and check it with a fresh installed raspbian os (full) without any mods if hardware itselve is ok

**Comment by alfrix** [comment]
you will have to test your hw and confirm it's working with some other distro as hawkeyexp, and then try to install it on raspbian lite or any os you like
but since this is not really a KS issue i will close this
