### ISSUE TITLE
Adding margins

### ISSUE THREAD

**Issue by robotfishe** [jordanruthe/KlipperScreen#558]
I'm using KlipperScreen on an old android phone with xserver, and the mount holding the phone blocks the edges of the display a bit, which makes hitting some buttons (extrude/retract length, etc) difficult. I've added a margin to the bottom of my screen by modifying base_panel.py to shrink the vertical size of the main window by 160 pixels:

            self.content.set_size_request(self._screen.width - action_bar_width - self.hmargin,
                                          self._screen.height - self.title_spacing - 160)

Is this something that could be implemented as a setting or config variable?

**Comment by alfrix** [comment]
i don't plan to keep those margins around in the code, so probably no, that would have to be done in a custom theme
