### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by AntoszHUN** [jordanruthe/KlipperScreen#561]
The error persists on the display. I don't know where to write. The display will be streaked if I wake up. Sometimes the image flickers as you live. Resolution cannot be selected after using the raspi-config command. The resolutions do not include the Raspberry Pi 7 "TFT resolution which would be 800x480. FluiddPi is installed. There was nothing wrong with Mainsail, it worked flawlessly. Who should I write to?
![DSC_0012](https://user-images.githubusercontent.com/45710979/160270116-b8b8be28-1bab-4548-840a-8d4cf6a82a32.JPG)

**Comment by alfrix** [comment]
it's very hard to understand you, from what i can gather it seems like a hardware related issue but, you say that it worked with mainsail ? maybe you mean mainsailos vs fluiddpi and it's a distro related thing?, idk ask in discord, this is not an issue with KS

**Comment by AntoszHUN** [comment]
> 

I understand. All right!
