### ISSUE TITLE
Can't shutdown or reboot Rapsberry Pi via KlipperScreen.

### ISSUE THREAD

**Issue by JWRu** [jordanruthe/KlipperScreen#564]
I have a problem with KlipperScreen since an update during the last days:
When I select Menu -> System -> System Shutdown -> I have two choices: "Continue" and "Cancel".  Both fields bring me back to the "System" menu - shutdown is not possible. The same happens with "System Restart.

**Comment by JWRu** [comment]
Update. It works when the printer is powered on, but it doesn't when the printer is powered off.

**Comment by alfrix** [comment]
this is most likely fixed in the 2.1 branch, you can test it if you want 
in ks folder:
```
git fetch
git checkout 2.1
```

restart klipper screen

**Comment by JWRu** [comment]
It works with branch 2.1

**Comment by JWRu** [comment]
When will the master branch be updated to fix this issue?

**Comment by alfrix** [comment]
done
