### ISSUE TITLE
Add more info to printing screen

### ISSUE THREAD

**Issue by 0x3333** [jordanruthe/KlipperScreen#565]
Is that possible to add more info in the printing screen?

Like Flow, Speed, filament. The same way Mainsail shows.

I can create a PR if accepted.

![image](https://user-images.githubusercontent.com/289289/160701740-35cfc12e-c0b0-4ab7-829f-288e18c44274.png)

**Comment by alfrix** [comment]
i haven't done any major changes to the job_status panel because Jordan said he was making a tabbed version,
the work is major, and needs to support 480x320 and vertical/portrait mode

**Comment by 0x3333** [comment]
I see. Well, I’ll work in a fork and see where I can go.
