### ISSUE TITLE
Add Layer Info as a First Class Information Line

### ISSUE THREAD

**Issue by adawalli** [jordanruthe/KlipperScreen#568]
While the M117 method described in the docs is an interesting workaround, it doesn't come for "free".

For example, if you also use the Telegram Plugin, you will get a telegram notification for every single layer (for every M117 message).

Would it be possible to add proper first-class support for this important piece of information to the primary home panel?

**Comment by svcsectool** [comment]
I see my MR was closed but I actually don't see the layer count on the new UI - am I missing something?

**Comment by adawalli** [comment]
I see my MR was closed, however, I don't see layer information in the new UI - where can I find it?

**Comment by alfrix** [comment]
click/press the Z position
all the information in the new main print status are buttons that take you elsewhere

**Comment by adawalli** [comment]
oh wow, that's amazing. thanks! looks great!
