### ISSUE TITLE
screen blur

### ISSUE THREAD

**Issue by AntoszHUN** [jordanruthe/KlipperScreen#570]
It was corrupted with the last update. The display does not turn off only the background color is visible. The controls disappear. But if I tap on him, he'll come back. Darkening does not work.

Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>
![DSC_0029](https://user-images.githubusercontent.com/45710979/161413199-308d5258-25ab-45b8-b0c8-9edee5966152.JPG)

**Comment by alfrix** [comment]
that is expected is DPMS is off, provide a logfile if that isn't the case

**Comment by AntoszHUN** [comment]
> that is expected is DPMS is off, provide a logfile if that isn't the case

DPMS is not turned off because you don't even know what it is.

**Comment by AntoszHUN** [comment]
I tried again. I turned off DPMS and it does the same. It doesn't darken.

**Comment by AntoszHUN** [comment]
Will there be a solution to this? The display still does not dim. Only the background color is visible.

**Comment by alfrix** [comment]
> I turned off DPMS and it does the same. It doesn't darken.

without DPMS it will not turn off

with DPMS it should, i will take a look using an HDMI tv to check if it's working

**Comment by AntoszHUN** [comment]
> 



> > I turned off DPMS and it does the same. It doesn't darken.
> 
> without DPMS it will not turn off
> 
> with DPMS it should, i will take a look using an HDMI tv to check if it's working

DPMS is on for me. As you can see in the picture.

![Screenshot_20220423-191845](https://user-images.githubusercontent.com/45710979/164916773-505df0f6-7af8-4449-bdca-e19ab6a40b94.png)

**Comment by alfrix** [comment]
i have tested dpms and it works as expected, so i dont think this is an issue with KS
you should ssh to the pi and enter this command to test your screen
```
DISPLAY=:0 xset dpms force off
```
if the screen turns off with the command then reopen this issue and provide KlipperScreen.conf
if the screen doesn't turn off then its an issue with your hardware or installation that doesn't work with DPMS

**Comment by AntoszHUN** [comment]
> i have tested dpms and it works as expected, so i dont think this is an issue with KS you should ssh to the pi and enter this command to test your screen
> 
> ```
> DISPLAY=:0 xset dpms force off
> ```
> 
> if the screen turns off with the command then reopen this issue and provide KlipperScreen.conf if the screen doesn't turn off then its an issue with your hardware or installation that doesn't work with DPMS

I gave the command via PUTTY. I got this in response and the display did not go dark.
![Új bitkép](https://user-images.githubusercontent.com/45710979/174479967-7a3a4143-db55-480c-817b-14e9b2617dc1.jpg)

**Comment by alfrix** [comment]
interesting, try the following command and tell me if it works:
```
DISPLAY=:0 xset s blank
```
then test again with this:

```
DISPLAY=:0 xset dpms force off
```
