### ISSUE TITLE
unable to use z_calibrate on delta.. 

### ISSUE THREAD

**Issue by danorder** [jordanruthe/KlipperScreen#575]
bug delta_calibrate method = manual doesn't use a defined probe so the menus are now disabled with recent commits. 
follow up request. ability to use delta_calibrate_manual instead of default zcalibrate "  eg run though the 7 points using the same menu.  
it could be macroed prior.  

example 
[gcode_macro Z_ENDSTOP_CALIBRATE] #klipperscreen workaround to run delta calibrate on klipper screen. 
#rename_existing: DELTA_CALIBRATE_MANUAL 
description: run klipper screen zoffset menu as delta calibrate manual instead. 
gcode: 
  G28
  DELTA_CALIBRATE METHOD=manual

lower nozzle using buttons , hit accept button  it moves to the next point etc ,  accept button  , save

**Comment by alfrix** [comment]
why method=manual and not automatic probe?

**Comment by danorder** [comment]
because not all deltas have a probe and, not all probes are accurate
enough. as listed in klipper docs. the recommended leveling procedure is
manual.
