### ISSUE TITLE
Software update not possible?

### ISSUE THREAD

**Issue by komandrik** [jordanruthe/KlipperScreen#577]
Today I'm trying to upgrade from version 0.2.1-5 to 0.2.1-14 via mainsail, KIAUX, terminal console and everywhere I get a refusal to update
![snap_screen_20220406151825](https://user-images.githubusercontent.com/40995038/161972835-be92fcbf-275d-45ea-9edf-08e1e6b8079b.png)

![snap_screen_20220406151857](https://user-images.githubusercontent.com/40995038/161972900-75f8e9af-17a6-441c-b5de-b18581298b5e.png)

Can I find out what has changed and how to fix it?

**Comment by alfrix** [comment]
my fault, sorry, i don-t understand why moonraker isn't marking the repo as dirty as it should

i think the easiest way will be
delete the contents of KlipperScreen folder
click on up refresh in the webui, the repo will be marked as dirty
click reset soft or hard

manually in via ssh
cd KlipperScreen
rm -rf *
git fetch
git reset --hard @

**Comment by axfb112** [comment]
> my fault, sorry, i don-t understand why moonraker isn't marking the repo as dirty as it should
> 
> i think the easiest way will be delete the contents of KlipperScreen folder click on up refresh in the webui, the repo will be marked as dirty click reset soft or hard
> 
> manually in via ssh cd KlipperScreen rm -rf * git fetch git reset --hard @
just tried but not vorking . same error

**Comment by alfrix** [comment]
weid, that should work

a couple more options
delete the entire folder
and do
git clone https://github.com/jordanruthe/KlipperScreen.git

uninstall and then reinstall via KIAUH

**Comment by miklschmidt** [comment]
@alfrix Someone forced pushed to master?

**Comment by alfrix** [comment]
it was me wrote master instead of dev, never force pushing again on anything it's just too dangerous, but now it's too late

**Comment by miklschmidt** [comment]
@alfrix You can disable force pushing to master in the repository settings on github, then it won't happen in the future :)
