### ISSUE TITLE
Print Status: Temp of Chamber 

### ISSUE THREAD

**Issue by 4noxx** [jordanruthe/KlipperScreen#584]
hello

how can i add the temperature of my chamber on this screen?

![image](https://user-images.githubusercontent.com/12627059/162611658-08ca9784-67fe-489b-832c-98ed8c39d5e4.png)

**Comment by alfrix** [comment]
current;y you can't have it there, i'm working on some updates, but it will take a while

for now, use the titlebar https://klipperscreen.readthedocs.io/en/latest/Configuration/#printer-options

**Comment by 4noxx** [comment]
like this?

![image](https://user-images.githubusercontent.com/12627059/162620417-2e4183b9-6ad7-460c-96f5-fb47adde9a3d.png)

**Comment by 4noxx** [comment]
hmm, i see only the printername on the top of the screen

![image](https://user-images.githubusercontent.com/12627059/162620922-e96cf3e7-292c-47ed-baa1-271ce4c1a45c.png)

![image](https://user-images.githubusercontent.com/12627059/162620988-887254a7-8389-49de-a5c4-31ffb09d3d30.png)

**Comment by 4noxx** [comment]
works now. 
think IP and Port are necessary
```
[printer Anet AM8]

moonraker_host: 127.0.0.1
moonraker_port: 7125
moonraker_api_key: False

titlebar_items: chamber, MCU, Pi

titlebar_name_type: None

use_dpms: True



```

**Comment by alfrix** [comment]
no they aren't,  the titlebar temp items don't load while printing, it's a bug

also use_dpms doesn't go under [printer] it goes under [main] do not put things blindly in your config please read and use what you need
