### ISSUE TITLE
Touch function not working

### ISSUE THREAD

**Issue by CoinNester** [jordanruthe/KlipperScreen#585]
Hello, I have managed to setup KlipperScreen on my old Samsung S6. Everything displays correctly but I can not activate any buttons by touch. I tried going through the Xserver mouse button definitions and tried each one and nothing has helped. I tried doing the calibration and it has not helped either. I tried using a tablet instead, same thing, got everything to display but I can't activate any of the buttons. Completely not responsive. I am connecting the screens using USB to the rpi4. Could someone please offer some advice on how to make this work. Thanks

**Comment by alfrix** [comment]
it's probably something related to the configuration ask in the [discourse](https://klipper.discourse.group/t/how-to-klipperscreen-on-android-smart-phones/1196) of android or on klipper-screen thread in discord
closing since we don't really provide support for android
