### ISSUE TITLE
How to define my own spi signal on OrangePi?

### ISSUE THREAD

**Issue by MS1987** [jordanruthe/KlipperScreen#591]
It is not an issue, just a question:
I use OrangePi, and want to use KlipperScreen with a [MKS TS35](https://github.com/willngton/3DPrinterConfig/tree/main/mks_ts35)(which uses spi interface).
I have installed Klipper and KlipperScreen through [Kiauh](https://github.com/th33xitus/kiauh), but no display now.Of course, this is normal, as the screen interface is different. So I think I should modify the interface definition of KlipperScreen to the screen, is there any way? Thanks!

**Comment by alfrix** [comment]
i cannot really provide support for this, KlipperScreen will work if you make your screen work, you can test everything with a desktop os and then install Klipperscreen
closing, since the issue tracker is for KlipperScreen issues, not hardware issues
