### ISSUE TITLE
The fan screen is unusable and not visible.

### ISSUE THREAD

**Issue by AntoszHUN** [jordanruthe/KlipperScreen#599]
I attached the pictures that do not show the fan control screen. This menu is simply useless.
LOG file not found in tmp folder.
![DSC_0012](https://user-images.githubusercontent.com/45710979/164884020-4e9f5647-b16a-4476-a13c-f215cc16d38d.JPG)
![DSC_0013](https://user-images.githubusercontent.com/45710979/164884036-aef50194-ec41-469a-86d8-d9066281786b.JPG)

Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

**Comment by alfrix** [comment]
i cannot fix it without a logfile

**Comment by AntoszHUN** [comment]
> 



> i cannot fix it without a logfile

KlipperScreen does not create a log file. Maybe there's an order for it? I can't find the KlipperScreen.log file anywhere.

**Comment by AntoszHUN** [comment]
if I think Klippy logos KlipperScreen? Here is the log file.
[klippy.log](https://github.com/jordanruthe/KlipperScreen/files/8546978/klippy.log)

**Comment by alfrix** [comment]
it's not the same, but it helped, this is caused by the name of the fan, you need to change the name of the fan to something without those special characters or it will not update

fixed crash with a77134d63b4895bfbc6a5e460b166dae261fed73

**Comment by AntoszHUN** [comment]
> 



> it's not the same, but it helped, this is caused by the name of the fan, you need to change the name of the fan to something without those special characters or it will not update
> 
> fixed crash with [a77134d](https://github.com/jordanruthe/KlipperScreen/commit/a77134d63b4895bfbc6a5e460b166dae261fed73)

Oh, I see. Thank you very much!
