### ISSUE TITLE
No scripts/install_service.sh ?

### ISSUE THREAD

**Issue by Maetsi** [jordanruthe/KlipperScreen#6]
Dont know if its just me, but I cant seem to find this 

> Using sudo, then run the service install script under scripts/install_service.sh and perform sudo systemctl daemon-reload. You can then start KlipperScreen with systemctl such as systemctl start KlipperScreen<

**Comment by jordanruthe** [comment]
That script was combined into the regular installation script. I've removed the text referring to manual installation as the latest install script should work for everyone. If you want, you're welcome to read through the script to manually run the commands.
