### ISSUE TITLE
[Enhancement] Add printer pause panel

### ISSUE THREAD

**Issue by bartoszwas** [jordanruthe/KlipperScreen#607]
First of all I want to thanks devs for such great job - this project is great and I will never return to 12864 lcds.

One thing I don’t like in klipper is filament runout sensor. In marlin it’s implemented way better. But, KlipperScreen can change that imho. 

What I’d like to have is a pause panel with purge, resume, cancel buttons. When filament sensor triggers and pauses printer, KlipperScreen could load that panel. (Filament switch state would be also nice to have on that panel)

I’ve made a fork with thisbut I’m not a python dev so probably I made it wrong way but if it works it is good 😄. 
https://github.com/bartoszwas/KlipperScreen

**Comment by alfrix** [comment]
that would be the extrude panel, i've noticed that when the pause comes from filament_sensor the move and extrude panels aren't added to the list as they should, this is a bug, but there is no need to create a panel

**Comment by bartoszwas** [comment]
ok, maybe don't create panel, but lets say optional automatic panel change when printer changes status to paused would be nice.
