### ISSUE TITLE
Cannot open virtual Console 2 and Any commands to fix it say Access denied.

### ISSUE THREAD

**Issue by Otterman88** [jordanruthe/KlipperScreen#613]
I get this error when running: `journalctl -xe -u KlipperScreen`
![2022-05-08](https://user-images.githubusercontent.com/105178446/167319749-5708f537-558b-4316-90a4-92b8c1e2f44b.png)
Run `cat /etc/X11/Xwrapper.config`
This should have the line `allowed_users=anybody` in it

Run `cat /etc/group | grep tty`
If your username is not listed under that line, you need to add it with the following command:

`usermod  -a -G tty pi` (if your username is not 'pi' change 'pi' to your username)

If it's still failing, try: `sudo apt install `xserver-xorg-legacy`

As a last resort add `needs_root_rights=yes` to `/etc/X11/Xwrapper.config`

When I try all of these under `cat /etc/group | grep tty` it says access denied.
Any idea what is happening?

**Comment by Otterman88** [comment]
It also shows the console instead of klipperscreen.

**Comment by alfrix** [comment]
`sudo usermod -a -G tty pi`
reboot
if it's still failing then
`sudo nano /etc/X11/Xwrapper.config`
add a new line with `needs_root_rights=yes`
save and reboot

**Comment by Otterman88** [comment]
That worked. Thanks!
