### ISSUE TITLE
[FR] macros with variables

### ISSUE THREAD

**Issue by tispokes** [jordanruthe/KlipperScreen#618]
Hi, I have some macros with 1 input field but also some with more (in my case 2), would be nice to be able to use this variables also in KlipperScreen`s macro menu.

Screenshot from Mainsail:
![image](https://user-images.githubusercontent.com/45465820/168557171-079a828e-9a23-41b8-82b3-9a27e5c3dd50.png)

Okay in this case I could use the corresponding submenu. But not for all use cases.

**Comment by alfrix** [comment]
done e658f562be29063d5a3f6b0f0de0fcbe69963f19
