### ISSUE TITLE
KlipperScreen Print list is empty

### ISSUE THREAD

**Issue by LazaroFilm** [jordanruthe/KlipperScreen#619]
KlipperScreen's print list shows as empty when Mainsail shows all the gcodes there. Tried refreshing, tired updating all software. 
It used to work fine before, then stopped after a recent update. 

klipper
v0.10.0-413-gdefce112
UP-TO-DATE
KlipperScreen
v0.2.2-4-g8accce0
UP-TO-DATE
moonraker
v0.7.1-570-g0164bb2
UP-TO-DATE
moonraker-telegram-bot
v1.4.3-0-gf753063
UP-TO-DATE
timelapse
v0.0.1-117-g3b23705
UP-TO-DATE
mainsail
v2.1.2
UP-TO-DATE

**Comment by alfrix** [comment]
i did some mods to the print panel, that may change this, for now wait until 0.2.3

> then stopped after a recent update 

this doesn't say anything useful without pointing out specifically on what version it worked, and testing back to back switching between those versions

**Comment by LazaroFilm** [comment]
Now updated to v0.2.3-14-geedf544 but the problem persists. I tried fumbling around with reverting to older versions but Couldn't make anything work since I use a kindle fire as screen on android and XSDL server...

**Comment by Nakamura-shot** [comment]
Same problem for me. I can't see any files in KlipperScreen's print list. I'm a new user and installed the current version of KlipperScreen.

**Comment by LazaroFilm** [comment]
Looks like this issue happens when you use KlipperScreen on an Android device with Material Dark color scheme for some reason. It works with Colorized theme. https://github.com/naruhaxor/AndroidKlipperScreen/issues/3

**Comment by Nakamura-shot** [comment]
It works for me for now :).
