### ISSUE TITLE
Disable the emergency stop button?

### ISSUE THREAD

**Issue by hardl0ck** [jordanruthe/KlipperScreen#622]
How to disable the emergency stop button? 
I'm using a hardware emergency stop button (kill_pin) and I want to disable the "emergency button" on the klipperscreen, because accidentally pressed it on the touch screen several times. 
I didn't find anything similar in the config.

**Comment by alfrix** [comment]
confirm emergency stop

![confirm](https://user-images.githubusercontent.com/1247237/169872473-fd0487d7-1a93-4444-9a1e-f7824f2cd390.png)
