### ISSUE TITLE
[FR] better tempetature selection

### ISSUE THREAD

**Issue by ssendev** [jordanruthe/KlipperScreen#626]
Currently in the Temperature screen above the graph, name and temperature are clickable.

Clicking on a temperature toggles the selection and clicking on a name opens a menu with hide/show, set temp, select

I think it would be better if clicking on a temperature would go to set temp and clicking on a name would toggle the selection. To restore the show/hide functionality clicking on the graph could open a menu (similar to the one which currently opens when clicking on a name) with the names and clicking on them would toggle their visibility.

**Comment by komandrik** [comment]
I have a small correction! Currently, you can click on the name of the heater and on its temperature, these are two separate tiles.
I suggest using a tile with a temperature display to instantly switch to the mode of setting the t° of this particular heater.

**Comment by komandrik** [comment]
> Currently in the Temperature screen above the graph, name and temperature are clickable.

They helped me often to solve this problem. Behind the path
**KlipperScreen/panels/main_menu.py -> Line 270**, if **self.popover_device = device** needs to add two rows
self.show_numpad(widget)
return

Lower butt yak is guilty of looking at the block:

KlipperScreen/panels/main_menu.py -> Line 270

![snap_screen_20220721220316](https://user-images.githubusercontent.com/40995038/180295582-aa654df6-4e45-40ea-b56e-0f953a2d6113.png)

https://user-images.githubusercontent.com/40995038/180295835-7650cace-d250-4b19-9343-d6a31571ddae.mp4

**Comment by ssendev** [comment]
Thanks @alfrix this looks good, but only fixes the MainPanel the TemperaturePanel has the same problem.

**Comment by alfrix** [comment]
It's not a "problem".
on the temp panel there are 3 functions (hide/show, select/unselect, set_temp) and 2 buttons, i use select/unselect, but i never use the keypad i find it quicker to deselect the bed and press a preset, rather than typing stuff with the osk.
for the moment it will remain like this until i figure out a better solution

**Comment by ssendev** [comment]
One solution would be to have the buttons do select/unselect, set_temp and move the hide/show functionality to a popup which appears when clicking on the graph. Could be the same black "speech bubble" as it is now but instead of (Show/Hide, Set Temp, Select/Deselect) it would list available temperature sensors (Show/Hide Extruder, Show/Hide Heater Bed, ...)

Another Solution would be to split the first button so there are three | color bar + Icon | Name | Temperature |

**Comment by alfrix** [comment]
> ...hide/show functionality to a popup which appears when clicking on the graph...

not a good idea the popup would have too many options in most cases

>Another Solution would be to split the first button so there are three | color bar + Icon | Name | Temperature |

interesting, but selections would not look very good, maybe

my solution at the moment would be 
name > select/unselect
temp > keypad
click graph > whole panel with options to hide show (like macros)
and maybe:
long press name/temp > popup
