### ISSUE TITLE
Probe_Calibrate

### ISSUE THREAD

**Issue by djbottolfson** [jordanruthe/KlipperScreen#628]
When I use the klipper console and probe_calibrate it takes my X/Y offset, whenever I do it from klipperscreen it doesn't honor my X/Y offset. The pictures are of probe_calibrate vs klipperscreen probe calibrate
![4FB61926-86C0-4C64-B792-F791B16EE78C](https://user-images.githubusercontent.com/31380124/171165980-1111dc0b-ff89-447d-867c-8deb25b57da5.jpg)
![AF3530A1-324C-47BD-92D0-CC07C4EEB5B5](https://user-images.githubusercontent.com/31380124/171165991-adb435af-3166-49fd-a507-a892334a83ca.jpg)
.

**Comment by alfrix** [comment]
KS will move the toolhead to the center and then probe_calibrate, it doesn't apply offsets in the zcalibrate panel

i will need a logfile or configfiles to see if you have something that could cause this and a more in-depth description on what you are doing and what you want to achieve

**Comment by alfrix** [comment]
if the default behavior doesn't suit you, change Z probe calibrate position:
https://klipperscreen.readthedocs.io/en/latest/Configuration/#printer-options
and since you haven't provided the logfile i cannot help you any further.
