### ISSUE TITLE
Should have a KlipperScreen restart button on the klipper disconnected screen

### ISSUE THREAD

**Issue by michelluccote** [jordanruthe/KlipperScreen#64]
On a few occasions I've had KlipperScreen disconnect from klipper and show the "Klipper has disconnected" screen. I need to send a log of this time since it never reconnected after I just did a Klipper restart from Fluidd. So I know my Klipper is running but KlipperScreen is stuck on this screen. My only options are Restart which I'm assuming means kipper restart and Firmware restart. 
I'm now stuck logging into my PI and restarting KlipperScreen or possibly restarting Moonraker. Or I can shut it down and restart the whole system.
This screen instead should have the extra option of restarting Moonraker or more importantly restarting KlipperScreen. This would just do the simple service stop and service start on KlipperScreen (or Moonraker) which would allow an easier recovery of my control screen.

**Comment by jordanruthe** [comment]
Ideally, this wouldn't be needed. However, I'll probably add a restart button in the system panel in the near future.

**Comment by jordanruthe** [comment]
This has been implemented in the system panel (which is accessible from the disconnected screen)
