### ISSUE TITLE
Scrollbar in configuration submenu with large font

### ISSUE THREAD

**Issue by xcasxcursex** [jordanruthe/KlipperScreen#646]
**Describe the bug**
A scrollbar appears when using the large font. 
![image](https://user-images.githubusercontent.com/58130821/173740715-d2c3b46a-f50a-43ba-ae24-ba122dfcb37d.png)
This is not the case with medium or small fonts.

**To Reproduce**
1. Change to large font

**Expected behavior**
Same as small/medium fonts

This is a non-standard setup using an Xvfb virtual display, so it might be just me. Sorry I couldn't find any screenshots to confirm this (I did try: did you know there are 26 pages of hits with images in the klipper-screen discord channel? lol).

Treat this as low priority if you like, it isn't bothering me terribly and has no functional impact.

**Comment by alfrix** [comment]
just to clarify, scrollbars are intended because in some languages you can have multiple lines in the buttons, and the user can add more buttons to the menu, so it's normal, in this case i think the margins can be tweaked a little, since it's so close
