### ISSUE TITLE
Is there a way to get multiple extruder icons in the top left?

### ISSUE THREAD

**Issue by XOIIO** [jordanruthe/KlipperScreen#664]
Hi there, just installed klipperscreen and I love it, makes the printer feel like a whole new, way more modern machine.

One thing that slightly bugs me however, is that in the upper left, I have icons for the primary extruder temp and bed temp, but not one for the secondary extruder temperature.

It's not a big issue, but if there's a way to add that one in I'd love it. I couldn't see anything about it in the documentation about the config file.

**Comment by alfrix** [comment]
Thank you for the kind words
>  have icons for the primary extruder temp [...] but not one for the secondary extruder temperature.

it's the currently active hotend, it should be activated with https://www.klipper3d.org/G-Codes.html?h=acti#activate_extruder 
in the macros T0, T1

currently there is no way to show all the extruders at the same time in the titlebar or job_status, if you want that feature then create a feature request.
