### ISSUE TITLE
Customize standard panels?

### ISSUE THREAD

**Issue by MikonosII** [jordanruthe/KlipperScreen#68]
Klipper screen is great!  Maybe I missed it but is there a way to customize the standard panels?  I would like to add an unload and load filament button on the extruder panel.

**Comment by jordanruthe** [comment]
Unfortunately, there's not a good way. That being said, I'm more than happy to make it so a Load/unload button appears in the extrude panel if there are corresponding macros.

**Comment by jordanruthe** [comment]
This was implemented with #250
