### ISSUE TITLE
[BUG] - Saving Z Endstop Deletes Last Line in Config

### ISSUE THREAD

**Issue by bugsysiegals** [jordanruthe/KlipperScreen#684]
**Describe the bug**
Saving babysteps from KlipperScreen deleted the last line of the config and causes my QGL to fail after the 4th corner.

**To Reproduce**
1. Go to KlipperScreen
2. Adjust Z offset during print
4. Save Z endstop
5. Reboot Klipper
6. Run QGL and it will give an error
7. Check your config and notice the last line #*# is missing.

**Expected behavior**
#*# last line should not be deleted and without it was trying to go to location 400 for me.

**Screenshots**
![image](https://user-images.githubusercontent.com/9281411/180631527-14b002b3-fe7e-4bd0-930b-ebdd33a0968e.png)

**Logfile**
Attach your [klipperscreen.log](https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/)

**Comment by alfrix** [comment]
ks sends to commands `Z_OFFSET_APPLY_PROBE` or `Z_OFFSET_APPLY_ENDSTOP` depending on the button, and then a `SAVE_CONFIG` it never writes the configuration directly, if you can reproduce what you are describing it's a bug in klipper.
closing as invalid.
