### ISSUE TITLE
[BUG] Cooldown temperatures

### ISSUE THREAD

**Issue by Tim2309** [jordanruthe/KlipperScreen#688]
With the new version 2.5.x the cooldown function set all temperatures to 0.
The Klipper cooldown can be configured, so it  doesn't change the chamber and controller temperature.

Is there a way to manually configure the cooldown or to exclude these tempertures?

**Comment by Tim2309** [comment]
Hi,
is there a new way to configure the cooldown? the cooldown button doesn't set any temperatures to 0.

**Comment by alfrix** [comment]
attach your logfile, it is probably a config error

**Comment by Tim2309** [comment]
my config and the klippy.log is in the zip
[KlipperScreen.zip](https://github.com/jordanruthe/KlipperScreen/files/9241885/KlipperScreen.zip)

**Comment by alfrix** [comment]
i was talking of klipperscreen.log, but with your config, i was able to reproduce the issue

it seems that i always had cooldown last and never tried to set it on top, this blank space bug was there since the pr for the cooldown preheat was accepted
good catch thank you
