### ISSUE TITLE
Print progress screen not updating.

### ISSUE THREAD

**Issue by mninja79** [jordanruthe/KlipperScreen#7]
When a print is complete. The progress screen while printing does not reset. When you restart a new print it shows the progress of the last completed print.

**Comment by jordanruthe** [comment]
Just pushed an update that will fix this problem.

**Comment by mninja79** [comment]
Cool, it works.
Another thing I noticed is for the first install the  .sh files in the scripts are not executable. Installation and start of KlipperScreen fails until the two files are executable.
