### ISSUE TITLE
[BUG] Calling Temperature Panel is not possible

### ISSUE THREAD

**Issue by schuessm** [jordanruthe/KlipperScreen#702]
Since the last update I can't call the temperature panel over the button temperature in the main screen

[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/9335688/KlipperScreen.log)

**Comment by alfrix** [comment]
this happens if your configuration is malformed, it's not a bug, the log is not complete to tell

**Comment by schuessm** [comment]
The log was completed. I deleted nothing there.
The problem ist solved now, it was the KlipperScreen.conf, I have since I installed moonraker and Klipperscreen, now I deleted the file and everything works fine. Thank you for your work and your help!
