### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by alidaf** [jordanruthe/KlipperScreen#704]
Installed Misc packages
Creating virtual environment
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0xf78ca950 (most recent call first):
./scripts/KlipperScreen-install.sh: line 101:  2454 Aborted                 pip --disable-pip-version-check install $requirements
Error: pip install exited with status code 0
Unable to install dependencies, aborting install.

**Comment by alfrix** [comment]
seeing #706 you fixed this issue
