### ISSUE TITLE
[BUG] Does not work with Hyperpixel4 despite claim

### ISSUE THREAD

**Issue by alidaf** [jordanruthe/KlipperScreen#706]
**Describe the bug**
Does not work with Hyperpixel4 - blank screen - no errors on logfiles.

**To Reproduce**
Follow installation steps from Pimoroni and Klipperscreen

**Expected behavior**
Working Display

**Logfile**
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/9386932/KlipperScreen.log)
[Xorg.0.log](https://github.com/jordanruthe/KlipperScreen/files/9386933/Xorg.0.log)

**Comment by alfrix** [comment]
this doesn't seem to be an issue with your display, but an issue with ks not being able to show the extruder for some reason and causing it to fail, i need to investigate it
