### ISSUE TITLE
Getting input from user

### ISSUE THREAD

**Issue by cdedwards** [jordanruthe/KlipperScreen#707]
I'm attempting to get this working on KlipperScreen. printer is not available 

[menu __main config bed_surface]
type: input
name: Bed: { printer.save_variables.variables.bed_surfaces[menu.input | int] }
method: printer.gcode.script 
input: {printer.save_variables.variables.bed_surfaces.index(printer.save_variables.variables.selected_bed_surface) | float }
input_min: 0.0
input_max: { ((printer.save_variables.variables.bed_surfaces | length) - 1) | float }
input_step: 1.0
gcode:
    SAVE_VARIABLE VARIABLE=selected_bed_surface VALUE="'{ printer.save_variables.variables.bed_surfaces[menu.input | int] }'"

**Comment by alfrix** [comment]
that syntax doesn't work for KlipperScreen that is for an old style graphical lcd

see the available options for the menu:
https://klipperscreen.readthedocs.io/en/latest/Configuration/#menu
