### ISSUE TITLE
[BUG] Cooldown Button should sets also temperature_fans to zero

### ISSUE THREAD

**Issue by bhelm** [jordanruthe/KlipperScreen#714]
**Describe the bug**
Cooldown sets all temperature targets to zero, including the cooling fans.

**To Reproduce**
Add a temperature fan
```
[temperature_fan psu]
pin: PD12
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PF5
target_temp: 45.0
pid_Kp: 20
pid_Ki: 0
pid_Kd: 0
min_temp: 10
max_temp: 60

control = pid
```
then hit the cooldown button

**Expected behavior**
Temperature fans are used to cool components so they do not overheat and get damaged. In my case, i use the temperature_fan to keep my PSU cool but quiet. Setting the target to zero causes the temperature_fan to hit its max temp, which can trigger a shutdown mid-print. Temperature fans can also be used to cool other components like steppers and the controller board.

So the expected behavior is that the very handy cooldown button leaves temperature_fans as they are.

Thank You! I enjoy using klipperscreen alot!

**Comment by alfrix** [comment]
> So the expected behavior is that the very handy cooldown button leaves temperature_fans as they are.

agreed, 0.2.6 will leave it as it was.

you can also configure 'cooldown' as it is a preheat setting
https://klipperscreen.readthedocs.io/en/latest/Configuration/#preheat-options
