### ISSUE TITLE
[BUG] Unable to parse "extruder" from [graph Printer] expected a number but got: False

### ISSUE THREAD

**Issue by coffeeandubuntu** [jordanruthe/KlipperScreen#726]
**Bug Overview**
I recently upgraded to KlipperScreen using a PITFT50. It has been working fine for a few weeks. After the most recent update of KlipperScreen, however, I now receive the following error when I power on my printer:

Unable to parse "extruder" from [graph Printer] expected a number but got: False

**Steps to reproduce the behavior:**
1. Power on printer.
2. 
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/9536129/KlipperScreen.log)
[printer.cfg.log](https://github.com/jordanruthe/KlipperScreen/files/9535912/printer.cfg.log)

**Comment by alfrix** [comment]
for bugs logs are needed, the log dumps your config without the api_key

**Comment by coffeeandubuntu** [comment]
> for bugs logs are needed, the log dumps your config without the api_key

Logs added to bug report.

**Comment by alfrix** [comment]
this was indeed a bug, fixed with 069097d
