### ISSUE TITLE
Moonraker_host and Moonraker_port not recognized

### ISSUE THREAD

**Issue by nickeeey** [jordanruthe/KlipperScreen#727]
What happened
Hi, i updated my moonraker after a long time and now i got this error on the screen:

https://imgur.com/a/Etw8qRp

This is my config:
[main]
moonraker_host: 127.0.0.1
moonraker_port: 7125

[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/9535691/KlipperScreen.log)

**Comment by alfrix** [comment]
your configuration is wrong host and port belongs to the printer section, since those values are the default

i would recommend you to remove all those menu entries from your config and leaving this:

```
[preheat FILA]
bed = 0
extruder = 210

[preheat MESH]
bed = 60
extruder = 150

[preheat PLA]
bed = 60
extruder = 150

[preheat ABS]
bed = 90
extruder = 240

#~# --- Do not edit below this line. This section is auto generated --- #~#

#~#
#~# [main]
#~# language = de_DE
#~# screen_blanking = 14400
#~# invert_z = True
#~# move_speed_xy = 85
#~# move_speed_z = 30
#~# 
```

More info https://klipperscreen.readthedocs.io/en/latest/Configuration/
