### ISSUE TITLE
Weird UART Error[BUG]

### ISSUE THREAD

**Issue by manashsharma20** [jordanruthe/KlipperScreen#731]
I have a BTT SKR Mini Clone. (Not into clones but that's what was available here). I keep getting error for the config file. The board has TMC2225 drives instead of TMC2209 as in official board. So I was using TMC2208 in config. As per examples seen in internet, Since All my drivers are connected in UART in write only mode( All connected to same UART PIN). When I use the config without UART_address I get an error to add UNIQUE UART_Address for each stepper drive. Now that I have added the unique address I get this error : ****. I have spent 3 days trying to figure this out myself. Any help would be of great help. I don't have SD Bootloader so I am doing Microcontroller flashing using STLINK.

This is my config file.

# Paste here and save your klipper configuration
# This file contains common pin mappings for the BIGTREETECH SKR mini
# E3 v2.0. To use this config, the firmware should be compiled for the
# STM32F103 with a "28KiB bootloader" and USB communication. Also,
# select "Enable extra low-level configuration options" and configure
# "GPIO pins to set at micro-controller startup" to "!PA14".

# The "make flash" command does not work on the SKR mini E3. Instead,
# after running "make", copy the generated "out/klipper.bin" file to a
# file named "firmware.bin" on an SD card and then restart the SKR
# mini E3 with that SD card.

# See docs/Config_Reference.md for a description of parameters.

[stepper_x]
step_pin: PB13
dir_pin: !PB12
enable_pin: !PB14
microsteps: 16
rotation_distance: 40
endstop_pin: ^PC0
position_endstop: 0
position_max: 235
homing_speed: 50

[tmc2208 stepper_x]
uart_pin: PC11
microsteps: 16
interpolate: True
run_current: 0.760
sense_resistor: 0.110
stealthchop_threshold: 100
uart_address: 0

[stepper_y]
step_pin: PB10
dir_pin: !PB2
enable_pin: !PB11
microsteps: 16
rotation_distance: 40
endstop_pin: ^PC1
position_endstop: 0
position_max: 235
homing_speed: 50

[tmc2208 stepper_y]
uart_pin: PC11
microsteps: 16
interpolate: True
run_current: 0.760
sense_resistor: 0.110
stealthchop_threshold: 100
uart_address: 0

[stepper_z]
step_pin: PB0
dir_pin: PC5
enable_pin: !PB1
microsteps: 16
rotation_distance: 8
endstop_pin: ^PC2
position_endstop: 0.0
position_max: 250

[tmc2208 stepper_z]
uart_pin: PC11
microsteps: 16
interpolate: True
run_current: 0.760
sense_resistor: 0.110
stealthchop_threshold: 100
uart_address: 0

[extruder]
step_pin: PB3
dir_pin: !PB4
enable_pin: !PD2
microsteps: 16
rotation_distance: 33.500
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: PC8
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PA0
control: pid
pid_Kp: 21.527
pid_Ki: 1.063
pid_Kd: 108.982
min_temp: 0
max_temp: 250

[tmc2208 extruder]
uart_pin: PC11
microsteps: 16
interpolate: True
run_current: 0.760
sense_resistor: 0.110
stealthchop_threshold: 100
uart_address: 0

[heater_bed]
heater_pin: PC9
sensor_type: ATC Semitec 104GT-2
sensor_pin: PC3
control: pid
pid_Kp: 54.027
pid_Ki: 0.770
pid_Kd: 948.182
min_temp: 0
max_temp: 130

[heater_fan heatbreak_cooling_fan]
pin: PC7

[fan]
pin: PC6

[mcu]
serial: /dev/serial/by-id/usb-Klipper_Klipper_firmware_12345-if00

[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3000
max_z_velocity: 5
max_z_accel: 100

[static_digital_output usb_pullup_enable]
pins: !PA14

[display]
lcd_type: st7920
cs_pin: EXP1_7
sclk_pin: EXP1_6
sid_pin: EXP1_8
encoder_pins: ^EXP1_5, ^EXP1_3
click_pin: ^!EXP1_2

[output_pin beeper]
pin: EXP1_1

[board_pins]
aliases:
    # EXP1 header
    EXP1_1=PB5,  EXP1_3=PA9,   EXP1_5=PA10, EXP1_7=PB8,  EXP1_9=<GND>,
    EXP1_2=PA15, EXP1_4=<RST>, EXP1_6=PB9,  EXP1_8=PB15, EXP1_10=<5V>

**Comment by alfrix** [comment]
KlipperScreen is an application that provides an UI to klipper, your errors seem to be klipper related
idk what could be going on on your setup
better ask in the [klipper discord server](https://discord.klipper3d.org/)
