### ISSUE TITLE
Large slow down when erroneous temperature reading

### ISSUE THREAD

**Issue by Deapper** [jordanruthe/KlipperScreen#732]
**Describe the bug**
After a firmware restart due to save_config my PT100 MAX31865 sometimes reports a huge temperature reading. 16million plus. Its only a small spike and only after a restart. Klipper screen then has a large slow down. Maybe 1 min to change off main screen. Once off main screen klipper responsiveness returns. Also once erroneous temperature reading falls off scale normal operation returns on main menu

**Comment by alfrix** [comment]
you haven't attached klipperscreen.log

**Comment by Deapper** [comment]
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/9616133/KlipperScreen.log)
