### ISSUE TITLE
Invalid config file[BUG]

### ISSUE THREAD

**Issue by Kornilis** [jordanruthe/KlipperScreen#737]
When the Printer boot up it always show that message on the screen. (happend since the last 2 Updates)
I compared the klipperscreen.cfg with an older version i have in my backup files but seams everything the same. 

![IMG_7500](https://user-images.githubusercontent.com/114732603/193231581-b43a5d1c-54f1-4091-b1b4-46a84d687d0a.JPG)

[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/9682435/KlipperScreen.log)

**Comment by alfrix** [comment]
not a bug, the option service was deprecated in v0.2.4 3 months ago, remove it from your config file

and as a recommendation remove all the config entries that you copied from defaults.conf, only change what you want to change, do not copy/paste blindly
