### ISSUE TITLE
[FR] Docker container?

### ISSUE THREAD

**Issue by kerta1n** [jordanruthe/KlipperScreen#744]
**Is your feature request related to a problem? Please describe.**
Will there be a Docker container for Klipperscreen?

**Describe the solution you'd like**
This way users who do run their 3D printing SW in Docker can experiment with different setups without installing all of the dependencies onto the host system like all of the X server dependencies. Also, this container could have a switch between displaying to its hosts' physical display, and only running a display server for clients (like Android devices) to connect to.

**Describe alternatives you've considered**
mkuf/prind has a container, but it involves using his compose stack.

**Additional context**

**Comment by alfrix** [comment]
Use [prind](https://github.com/mkuf/prind)

**Comment by kerta1n** [comment]
As I listed earlier, I had tried to use prind, but it was not that easy to use since I had to use Klipper/Moonraker/Mainsail from his stack, and was not as configurable as I'd hoped it to be. Is that the only solution there is then?
