### ISSUE TITLE
[BUG] KS doesn't trigger BED_SCREWS_ADJUST command when clicking the corner icons

### ISSUE THREAD

**Issue by Gil80** [jordanruthe/KlipperScreen#745]
**Describe the bug**
KlipperScreen doesn't run the actual BED_SCREWS_ADJUST command when clicking the corner icons.
Instead, the printhead is crushing the probe on the bed at an incorrect coordinate.
**Note**: I'm using a magnetic klicky probe which is lower than the nozzle, hence I believe KS is trying to get the nozzle to touch the build plate, therefore crashing the probe on the bed. 

**To Reproduce**
1. Enable `[screws_tilt_adjust]` in `printer.cfg` with the relevant screws names and coordinates
2. In KS, navigate to Bed Level
4. Click on one of the corner icons

**Expected behavior**
To get the probed exactly above the selected screw and probe it, as it does when clicking the `screws adjust` icon. It should probe the coordinate of the selected screw with the probe and not with the nozzle.

**config**
```
[screws_tilt_adjust]
screw1: 25, 5
screw1_name: front left screw
screw2: 195, 5
screw2_name: front right screw
screw3: 195, 175
screw3_name: rear right screw
screw4: 25 ,175
screw4_name: rear left screw
horizontal_move_z: 7
speed: 300
screw_thread: CW-M4
```
These coordinates are the above `screws_tilt_adjust + probe offset`:
https://cdn.discordapp.com/attachments/431559228050636820/1026832693616451675/IMG_20221004_151058.jpg

Why does KS instruct the printer to move the nozzle and not the probe above the screw?
Why does it keep lowering the printhead after the klicky probe is triggered?

**Comment by alfrix** [comment]
> I believe KS is trying to get the nozzle to touch the build plate, 

Yes, it's the intended behavior https://klipperscreen.readthedocs.io/en/latest/Screws/

> To get the probed exactly above the selected screw and probe it

last time i checked SCREWS_TILT_CALCULATE always measures all the screws, it can't measure individual screws, so what you are asking is not possible

> Why does KS instruct the printer to move the nozzle and not the probe above the screw?

https://klipperscreen.readthedocs.io/en/latest/Screws/#why-the-probe-offset-is-applied-to-screws_tilt_adjust

>  Why does it keep lowering the printhead after the klicky probe is triggered?

i'm guessing here: unless you use the probe as virtual-endstop klipper will not stop moving if the probe is triggered
