### ISSUE TITLE
UpdateManager problem

### ISSUE THREAD

**Issue by nicedevil007** [jordanruthe/KlipperScreen#75]
Heya @jordanruthe,

just added your update possibility to moonraker and it is not working. Maybe something changed in the last fixes/commits?

That is my snippet of the moonraker.conf

```
[update_manager]
[update_manager client fluidd]
type: web
repo: cadriel/fluidd
path: ~/fluidd


[update_manager client KlipperScreen]
type: git_repo
path: /home/pi/KlipperScreen
origin: https://github.com/jordanruthe/KlipperScreen.git
env: /home/pi/.KlipperScreen-env/bin/python
requirements: scripts/KlipperScreen-requirements.txt
install_script: scripts/KlipperScreen-install.sh
```

And this is  what is shown to me in the webui:

![image](https://user-images.githubusercontent.com/17103076/107111215-784d4600-684e-11eb-957b-84b7544b4338.png)

**Comment by nicedevil007** [comment]
![image](https://user-images.githubusercontent.com/17103076/107148583-48886600-6954-11eb-82d7-254a7bcac85c.png)

**Comment by Elektrickser** [comment]
How you solved? I have the same problem.

**Comment by nicedevil007** [comment]
> How you solved? I have the same problem.

Click on the link of the other referenced post ;) I wrote everything there.

**Comment by Elektrickser** [comment]
Thanks, I was blind.
