### ISSUE TITLE
Run macro from button

### ISSUE THREAD

**Issue by TheLion** [jordanruthe/KlipperScreen#756]
Is there an option to run a macro from a button in the Actions menu?

I have a custom PARK macro that I use often and would like to use it from the Actions menu.

Didn't find any such option in the configuration guide.

**Comment by alfrix** [comment]
> Didn't find any such option in the configuration guide.

https://klipperscreen.readthedocs.io/en/latest/Configuration/#menu

for example 
```
[menu __main actions mybuttonname]
name: My awesome button
icon: home
method: printer.gcode.script
params: {"script":"My_Macro"}
```

to have it while printing you need to change __main to __print

you can take a look at the default config to have a reference:
https://raw.githubusercontent.com/jordanruthe/KlipperScreen/master/ks_includes/defaults.conf
