### ISSUE TITLE
[FR]Exclude object 

### ISSUE THREAD

**Issue by Code0rca** [jordanruthe/KlipperScreen#757]
I’d like to be able to exclude an object without having to open mainsail on my computer I’m sure others would also like this feature if it isn’t already included and I’m just an idiot

**Comment by alfrix** [comment]
it is in the cancel dialog if at least 2 objects are present
![exclude](https://user-images.githubusercontent.com/1247237/196044110-a314aafc-2f76-4c90-95bc-fa6e9e14d36a.png)
![exclude_](https://user-images.githubusercontent.com/1247237/196044109-a06cc5ce-ac59-4965-ab70-aec95de074ba.png)

**Comment by Code0rca** [comment]
Thank you very much I figured I was just stupid but apparently I’m stupider lol

**Comment by KennyVB** [comment]
was looking for this! thanks!
