### ISSUE TITLE
[BUG] Add printer function seem to be broken

### ISSUE THREAD

**Issue by Guilouz** [jordanruthe/KlipperScreen#759]
**Describe the bug**
It's not possible anymore to add a new printer in case of multiple instance of Klipper and Moonraker

**To Reproduce**

Change Printer button no longer appears on the splash screen

In settings there is no possibility to add a new printer in Printer Connections settings

**Expected behavior**
Possibility to add a new printer

**Comment by alfrix** [comment]
> In settings there is no possibility to add a new printer in Printer Connections settings

are you talking about the settings panel? that only shows the configured printers it never had the ability to add new printers

**Comment by Guilouz** [comment]
@alfrix what is this code for in the settings panel?

self.labels['add_printer_button'] = self._gtk.Button(_("Add Printer"), "color1")

When multiple instances is configured in klipper, klipperscreen only see the first one and it’s impossible to switch to another one.

**Comment by alfrix** [comment]
> `self.labels['add_printer_button'] = self.gtk.Button(("Add Printer"), "color1")`

That is a button created by Jordan, not connected or added to anything, it's like a reminder/TODO

> When multiple instances is configured in klipper, klipperscreen only see the first one and it’s impossible to switch to another one.

KlipperScreen needs the printers defined in the configuration file, there is no 'discovery' or automatic anything.

tipically multiple instances on the same host are defined by changing ports to talk to the different moonraker instances

```
[printer Ender 3 Pro]
moonraker_host: 127.0.0.1
moonraker_port: 7125
[printer Second printer same host]
moonraker_host: 127.0.0.1
moonraker_port: 7126
```
[see the docs for more options](https://klipperscreen.readthedocs.io/en/latest/Configuration/#printer-options)

**Comment by Guilouz** [comment]
@alfrix Thanks for this info I understand now why add printer doesn’t appear.
