### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by talrhv** [jordanruthe/KlipperScreen#766]
Updated version to my Hebrew translation files. Please include them in the next update.

[Hebrew mo](https://drive.google.com/file/d/1iMhcUwwe3JO7ixQ_z-hNpFj3F6t1pPAx/view?usp=drivesdk) 

[Hebrew po](https://drive.google.com/file/d/1Jg5jaadqk_x35APP6gJTXEwaz1sfdjFe/view?usp=drivesdk)

**Comment by alfrix** [comment]
Thank you!
