### ISSUE TITLE
[FR]Possibility to use a Filament Flow Sensor

### ISSUE THREAD

**Issue by Nogtu** [jordanruthe/KlipperScreen#769]
I have often had cases where the nozzle clogs during the printing process and no longer conveys filament, but the printing process continues. It has happened after several hours that no more filament was printed after a few layers, but the printer simply continues to "print".

For such a case, a filament flow sensor would be very interesting. For example, you could implement and use the filament sensor of the Ultimaker S5. So far, there is only a way to program filament sensors that register whether filament is present or not. However, a flow sensor would be the right choice for this.

**Comment by alfrix** [comment]
both the [filament_motion_sensor](https://www.klipper3d.org/Config_Reference.html?h=screw+tilt#filament_motion_sensor) and [filament_switch_sensor](https://www.klipper3d.org/Status_Reference.html#filament_switch_sensor) they are shown in the extrude panel, KlipperScreen is just a GUI implementations or modifications to sensors should be done in Klipper.
