### ISSUE TITLE
Not returning to Status Screen

### ISSUE THREAD

**Issue by bruce356** [jordanruthe/KlipperScreen#77]
All software firmware up to date using Kiauh for that and installation.
Have found a problem with returning to the job "status screen" after a print cancel or emergency stop option is selected before the print has actually started (if cancelled while print job is in progress this problem does not occur).
E.G. while the bed is heating, press cancel, the bed continues to heat until it reaches its temperature (a klipper thing), after reaching preset temperature the print is then cancelled.
Now after the cancel, select the same object/model again to print and instead of showing the "Status Screen" it returns to the  Print screen.

**Comment by jordanruthe** [comment]
Can you post your KlipperScreen.log file? Ideally pull the file shortly after you've replicated the issue.
