### ISSUE TITLE
Keyboard Symbol ⌫ not recognized

### ISSUE THREAD

**Issue by Guilouz** [jordanruthe/KlipperScreen#770]
On RaspiOS Lite ⌫ keyboard symbol is not recognized, it's look like in UTF-16 :

![IMG_0129](https://user-images.githubusercontent.com/12702322/198840798-078c735b-379e-468c-9659-1218c1abe3a3.jpeg)

On Ubuntu LTS no problem :

![IMG_0130](https://user-images.githubusercontent.com/12702322/198840815-4f3a8ed8-8611-432e-9ac5-3341d0d4b30a.jpeg)

Any idea what is missing ? Font missing ?

**Comment by alfrix** [comment]
not really a "bug", you are missing a font glyph, installing a font package like fonts-freefont-ttf should fix this
don't worry too much, i have plans to remove them and replace them with icons like the keypad
![2](https://user-images.githubusercontent.com/1247237/198877313-db3c3638-363d-4ea4-afcf-eb4d86fb23a0.png)

**Comment by Guilouz** [comment]
Thanks for your reply.
