### ISSUE TITLE
[FR]  Auto-Select bed on temp panel when clicking bed temperature on print_status

### ISSUE THREAD

**Issue by marcin-koziol** [jordanruthe/KlipperScreen#783]
**Describe the bug**
When clicking on bed temperature in print status view, the temperature panel shows, but extruder is selected

**To Reproduce**
1. Start printing
2. Click on bed temperature
3. You have to select bed again to change value

**Expected behavior**
After clicking bed temp. button, the temperature, bed should be selected 

Please close this issue if that behavior is desired. If not - I can make a PR.

**Comment by alfrix** [comment]
This was by design since the most common use case is changing extruder temp usually because of speed changes, it's not common to change bed_temp after print started, you can attempt to do it if you want
