### ISSUE TITLE
[FR] Check for homing_override and raise Z before deploying BL Touch

### ISSUE THREAD

**Issue by tinymachines3d** [jordanruthe/KlipperScreen#784]
Same issue as [748](https://github.com/jordanruthe/KlipperScreen/issues/748) but only when homing_override is used instead of safe_z_home

**Describe the solution you'd like**
Check to see if homing_override is used (or if safe_z_home is not) and in the case where there is no safe_z_home, use the sample_retract_dist: value from [bltouch] as a raise value to allow homing.

**Comment by alfrix** [comment]
shourld be resolved with 0ca410acba5df3910017d9ddb02c1c630cd8a0e9

**Comment by tinymachines3d** [comment]
Confirmed that it works as expected! Thank you @alfrix
