### ISSUE TITLE
KlipperScreen bugged theme

### ISSUE THREAD

**Issue by BobTwins** [jordanruthe/KlipperScreen#793]
Hi!!
I just installed a 7" touch screen to my Rasp Pi 4 along with Klipperscreen and everything was fine until I changed the theme to "Colorized". Since then, my screen shows "No Signal". I tried to reinstall KlipperScreen but nothing. It might have to be a configuration setting. Any suggestion will be much appreciated.

**Comment by alfrix** [comment]
i'm sure changing theme is not the issue, you need to provide KlipperScreen.log if you want help

**Comment by alfrix** [comment]
no log file was provided closing
