### ISSUE TITLE
Save Z-Offset is gone...

### ISSUE THREAD

**Issue by LoboThirteen** [jordanruthe/KlipperScreen#795]
Since the last update, the ''Save Z-Offset'' function is no longer displayed after a print if you have changed the Z-Offset in ''Fine Tuning'' during the print...

**Comment by alfrix** [comment]
tested and seems to be working correctly, provide klipperscreen.log for checking if there is something wrong in your case

**Comment by LoboThirteen** [comment]
Where can i find the log file?

**Comment by LoboThirteen** [comment]
I found it...
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/10049353/KlipperScreen.log)
