### ISSUE TITLE
[FR] Single line for Elapsed/Remaining time in job_status screen

### ISSUE THREAD

**Issue by guestisp** [jordanruthe/KlipperScreen#802]
Currently, Elapsed time and remaining time are on 2 different lines.

Putting them on a single line would free some space that could be used to increase even more the font size for the text.

**Comment by alfrix** [comment]
except on ultrawide, (which needs a better layout) in general there is no space to do this, and the max setting implemented for font-size is as big as it can be, doing this would not make it better
