### ISSUE TITLE
Screen won't wake up, KlipperScreen service restart helps sometime

### ISSUE THREAD

**Issue by blonestar** [jordanruthe/KlipperScreen#804]
### Discussed in https://github.com/jordanruthe/KlipperScreen/discussions/700

<div type='discussions-op-text'>

<sup>Originally posted by **jrose78** August 14, 2022</sup>
I have a pi 7" touchscreen and everything works great except when the screen goes to sleep I can't wake it back up. I figured I was missing something and did a couple searches on how to wake the screen back up, but I didn't find an answer so I figured I would post here. I have a pi 4 and the 7" touchscreen. I have of course tried touching the screen until it started to feel uncomfortable.  I hit the power button and turned it off and back on but it say no signal.  Any ideas?

Thank you!

Edit: Just figured out that if I power off the monitor and then power it back on when it says no input and I tap the screen it comes back to life.  So when the screen is off it does not register touches.</div>

**Comment by hawkeyexp** [comment]
Same problem on a waveshare 5" - seems the dpms reworks form latest commits are causing this - currently touchscreen reacts to touch but screen stays blank.
