### ISSUE TITLE
No logs and not working KlipperScreen on Android

### ISSUE THREAD

**Issue by 110Tim706** [jordanruthe/KlipperScreen#811]
I tried to install Klipperscreen to use it as screen for my printer. I installed it via kiauh and it seems fine. After, that, I just copy pasted every line of this guide (https://klipperscreen.readthedocs.io/en/latest/Android/). I just get a blue picture in the app, so I want to check for the logs, but there aren't in tmp nor in logs.
![F9E5AE17-90F9-4182-9A82-AF174DDCCBCB](https://user-images.githubusercontent.com/88311837/204058025-cfb3c55b-7d56-4ba3-b594-316ef07b39a2.jpg)
<img width="408" alt="Forth" src="https://user-images.githubusercontent.com/88311837/204058030-13626c75-e9ca-4224-a83a-9997ae5c1da6.PNG">
<img width="401" alt="Third" src="https://user-images.githubusercontent.com/88311837/204058031-998603a1-5b7d-4ce6-bb99-baae4578df51.PNG">
<img width="601" alt="Second" src="https://user-images.githubusercontent.com/88311837/204058033-616f9f80-cb06-46cb-9bdb-4b44937f9e21.PNG">
<img width="721" alt="First" src="https://user-images.githubusercontent.com/88311837/204058034-8cf7a4a0-307e-4817-acbc-ca15768ccc28.PNG">

**Comment by alfrix** [comment]
KlipperScreen.log are on ~/printer_data/logs or /tmp/ it's explained in https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/

you are mixing methods  for android via wifi delete that script and just follow https://klipperscreen.readthedocs.io/en/latest/Android/#wifi the script should only contain the line mentioned in the docs,  

the :0 at the end of the ip is the display number not a port

**Comment by 110Tim706** [comment]
Thx for your reply figured it out an hour ago but this are the things I change. Maybe This will help someone else.
