### ISSUE TITLE
[BUG] Layout issue when multiple printers are defined

### ISSUE THREAD

**Issue by Guilouz** [jordanruthe/KlipperScreen#813]
**Describe the bug**
Layout issue when multiple printers are defined

**To Reproduce**
Enable multiple printers in KlipperScreen.conf

**Expected behavior**
Layout adjustment

**Screenshots**

When multiple printer are defined : 

![IMG_0202](https://user-images.githubusercontent.com/12702322/204071372-786547ba-6440-4307-b9bc-7cc5ad058c28.jpeg)

![IMG_0203](https://user-images.githubusercontent.com/12702322/204071377-663e2844-5f03-4a0e-a8f3-26a78ffa6049.jpeg)

When only one printer is defined no issue : 

![IMG_0204](https://user-images.githubusercontent.com/12702322/204071385-cfd9bfc7-d147-44c6-9391-ed5673c9c5d3.jpeg)

**Comment by alfrix** [comment]
it doesn't seem to happen on this repo 

![1](https://user-images.githubusercontent.com/1247237/204088461-d58f0779-0e13-49e2-a2bc-fcab5c9ad08e.png)
i even duplicated the ws message 
![2](https://user-images.githubusercontent.com/1247237/204088463-675ebe26-eaec-4b67-90ff-a30c3416924c.png)

checked the source of your  repo, also didn't found anything that could be the cause

the only source that i could see that could be causing this is `self._screen.base_panel.content.get_allocation()`

i will change it to a screen width, it should be more stable

**Comment by Guilouz** [comment]
@alfrix Could this be related to the fact that I modified the printer select panel?

To obtain this : 

![316592483_953648515606801_8103995564934004347_n](https://user-images.githubusercontent.com/12702322/204089262-f23dd44a-ada6-41c0-8c9b-0e8c00ffda38.png)

Before your recent scale changes, all was working good.

**Comment by Guilouz** [comment]
@alfrix Just clonned your repo, same issue.

My screen have a resolution 1024x600

![IMG_0206](https://user-images.githubusercontent.com/12702322/204091227-139496da-dde7-49f2-85c1-d3524eed27b4.jpeg)

![IMG_0207](https://user-images.githubusercontent.com/12702322/204091230-bed93afa-9fb4-4c31-be30-85ddc8e20850.jpeg)

**Comment by alfrix** [comment]
try changing splash_screen line 46:
from: `self.labels['actions'].set_size_request(self._screen.base_panel.content.get_allocation().width, 0)`
to: `self.labels['actions'].set_size_request(self._gtk.get_content_width(), -1)`

**Comment by Guilouz** [comment]
@alfrix Yes it's now ok. Thanks.
