### ISSUE TITLE
[BUG] Display cant be woken up from set standby

### ISSUE THREAD

**Issue by dadonali** [jordanruthe/KlipperScreen#814]
I have the problem that the display randomly can no longer be woken from standby. 
That means, the display goes into standby after the set time.
If I then click on the display, the display stays black and you can only see the backlight. 
This can only be fixed by restarting Klipperscreen.

![316727445_1126200118090016_4521679176221013465_n](https://user-images.githubusercontent.com/100767028/204079098-736f62f6-96b7-4346-96e7-e457f0555772.jpg)

**Comment by alfrix** [comment]
how to get the log: https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/

**Comment by dadonali** [comment]
See the Log attached

[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/10096752/KlipperScreen.log)

**Comment by alfrix** [comment]
you are  on v0.2.9-14 818f1ab the error should be fixed with c0ffa41 you need to update, sorry for the trouble

**Comment by dadonali** [comment]
but v0.2.9-14 is the latest version for me? where can i get the c0ffa41 ? or you push the new version in a few days?
