### ISSUE TITLE
[BUG] Boot Loop after Update 

### ISSUE THREAD

**Issue by dadonali** [jordanruthe/KlipperScreen#817]
I update to the newest version, now im in a bootloop of klipperscreen and the screen doesnt load the GUI.

See only the terminal on the screen for about 2-3 sec, black screen, again the terminal.

<img width="601" alt="Bildschirm­foto 2022-11-26 um 20 34 58" src="https://user-images.githubusercontent.com/100767028/204106192-f3ce6a73-ce17-4d23-b8a8-750baebc36c1.png">

[KlipperScreen (5).log](https://github.com/jordanruthe/KlipperScreen/files/10096916/KlipperScreen.5.log)

https://user-images.githubusercontent.com/100767028/204106295-efa32fca-a086-424f-8477-d78d5fd4a97e.mp4

**Comment by Aaronhrndz** [comment]
Mine shows same behaviour

**Comment by dadonali** [comment]
complete new installation doesnt fix the issue

**Comment by Aaronhrndz** [comment]
v0.2.9-60-ge9df355 and v0.2.9-61-ga61a74d versions shows the same behaviour

**Comment by alfrix** [comment]
the log can be obtained via journalctl  if it's not dumped as explained in https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/


you can also rollback by n amount of commits to bisect where it starts working again:
```sh
cd KlipperScreen
git --reset --hard @~5
```

or do `git --reset --hard @c630178f0ca62d76195940af01c76db0d0afd7fe`

with a hash  from the commit list
https://github.com/jordanruthe/KlipperScreen/commits/master

**Comment by dadonali** [comment]
Doesnt work for me :(

<img width="587" alt="Bildschirm­foto 2022-11-26 um 21 37 14" src="https://user-images.githubusercontent.com/100767028/204108070-d5f33bb7-10da-4bde-8aa8-6bc16341df70.png">

**Comment by Aaronhrndz** [comment]
> Doesnt work for me :(
> 
> <img alt="Bildschirm­foto 2022-11-26 um 21 37 14" width="587" src="https://user-images.githubusercontent.com/100767028/204108070-d5f33bb7-10da-4bde-8aa8-6bc16341df70.png">

try with `git` reset --hard @c630178f0ca62d76195940af01c76db0d0afd7fe`

**Comment by alfrix** [comment]
i'm sorry i wrote it wrong it's
`git reset --hard @~5`
where 5 is the number of commits/changes

**Comment by dadonali** [comment]
okay git reset --hard @~5 work for me :) now lets see if the blank screen issue is fixed

**Comment by Aaronhrndz** [comment]
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/10097020/KlipperScreen.log)
Here's a log after restoring 5 commits ago, sadly not working. I've deleted also my custom klipper-config overrides for klipperscreen
