### ISSUE TITLE
Streched on 64Bit

### ISSUE THREAD

**Issue by Steven2k6** [jordanruthe/KlipperScreen#824]
I recently changed to 64Bit and now my KlipperScreen is streched.
I have a 480x320 RPI 3.5" Display

[config.txt](https://github.com/jordanruthe/KlipperScreen/files/10114002/config.txt)
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/10114003/KlipperScreen.log)
[klippy.log](https://github.com/jordanruthe/KlipperScreen/files/10114004/klippy.log)

**Comment by alfrix** [comment]
after a fresh install of raspbian os lite 64bit, i can confirm that your issue is something that you changed/broke
as you can see in the logs it was correct, until you changed something
![imagen](https://user-images.githubusercontent.com/1247237/204784345-b686290f-08e2-4218-8a2c-56706ba497a2.png)

**Comment by Steven2k6** [comment]
It´s a bit weird, because it worked before changing to 64Bit from an 32Bit installation of an Mainsail-Image, by adding arm_64bit=1

**Comment by alfrix** [comment]
closing as not a klipperscreen bug install your screen properly with the manufacturer instructions
