### ISSUE TITLE
[BUG] filament sensor status 

### ISSUE THREAD

**Issue by CIS94500** [jordanruthe/KlipperScreen#825]
**Describe the bug**

the status of the filament sensor is not detected, the activation and deactivation function with the switch works

**To Reproduce**

1. Go to actions
2. Click on Extrusion

**Screenshots**

![s1](https://user-images.githubusercontent.com/83906767/204585466-b65f9f70-c4d3-4081-9bb9-22ccf5aebf2d.JPG)

**Logfile**
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/10115005/KlipperScreen.log)

**Comment by Guilouz** [comment]
I can confirm this too.

**Comment by alfrix** [comment]
i think this is an initial state problem, if you have the panel open it seems to work for me

does the status works if the panel is open when the filament is triggered?

**Comment by Guilouz** [comment]
@alfrix yes this happens when panel is opening, if you disable and enable it again, it's ok.

it's happens since a recent PR.

**Comment by CIS94500** [comment]
when the panel is open and I go from 0 to 1 or from 1 to 0, the color of the switch disappears

if I remove the filament the state does not change.

![s2](https://user-images.githubusercontent.com/83906767/204794915-af3c21e0-0238-451b-b9d7-e199944bfe83.JPG)
![s3](https://user-images.githubusercontent.com/83906767/204794942-a2ab4e71-775a-4781-a39f-de9e392a703d.JPG)
