### ISSUE TITLE
[BUG] SPI Screen not working when changing to 64Bit

### ISSUE THREAD

**Issue by Steven2k6** [jordanruthe/KlipperScreen#827]
When I change to 64Bit adding `arm_64bit=1` to the config.txt, the Screen keeps black after restarting.
And when I change back to 32Bit by removing the line, the Screen works after Restarting.

**Comment by alfrix** [comment]
not a klipperscreen bug, you need to install the screen according to the manufacturer instructions 

as help i can tell you that is never changing a value and done
