### ISSUE TITLE
Layout issue with scrollbar

### ISSUE THREAD

**Issue by Guilouz** [jordanruthe/KlipperScreen#828]
How can I remove this unsightly scrollbar? It has appeared since recent PRs.

Before the Temp (°C) text and 4 items fit perfectly into the frame.

Note: Icons scaling is not good either.

Before:

![Capture d’écran 2022-12-01 à 00 25 07](https://user-images.githubusercontent.com/12702322/204929645-6d413186-98dc-40bb-8be9-acceb412ed19.jpg)

After:

![IMG_0228](https://user-images.githubusercontent.com/12702322/204929671-165f4c7a-238e-41d0-90eb-dcd64332cd8f.jpeg)

**Comment by Guilouz** [comment]
@alfrix Can you point me what can be modified to change that ?

**Comment by alfrix** [comment]
most of the spacing is done in the css so you can gtk inspector to tweak it on the fly, in my opinion scaling needs a lot more work to be more integrated and more easily tweakable

**Comment by Guilouz** [comment]
Last PR fix issue. Thanks.
