### ISSUE TITLE
Color for Powerplug on "deactivated" State is different than on other menus

### ISSUE THREAD

**Issue by nicedevil007** [jordanruthe/KlipperScreen#83]
Just small cosmetic thing.

The color for the font is different during a print of the power plugin in comparison to services f.e.

It is much darker:
![image](https://user-images.githubusercontent.com/17103076/107878984-877b6600-6ed6-11eb-9a92-8dd5c09b5036.png)

Here the services in "light grey":
![image](https://user-images.githubusercontent.com/17103076/107879001-96621880-6ed6-11eb-884c-3d55dce32c83.png)

**Comment by jordanruthe** [comment]
This looks to be a fluidd issue, not KlipperScreen. You should repost this on the fluidd github issues.

**Comment by nicedevil007** [comment]
> This looks to be a fluidd issue, not KlipperScreen. You should repost this on the fluidd github issues. 

Haha lol! Sry, was sure I was on the Right repo to post 😇😂😂😂
