### ISSUE TITLE
[FR] Add software switch to power off printer

### ISSUE THREAD

**Issue by lucaee** [jordanruthe/KlipperScreen#833]
**Is your feature request related to a problem? Please describe.**
In case you stay at your printer while printing, you don't want it to shut down after printing. 
But power printer works only with a macro at the end of the gcode.

**Describe the solution you'd like**
Add a software switch to the printing screen, which sends gcode when finished printing. So everytime you start a print, you can decide, if the printer should power off when finished or not.

Thank you

**Comment by alfrix** [comment]
this is not something that i will implement, thank you Misterke for providing a solution to this
