### ISSUE TITLE
[BUG] Camera panel issue

### ISSUE THREAD

**Issue by Guilouz** [jordanruthe/KlipperScreen#839]
Since recent PR with camera support there is an issue with camera panel.

When clicking on camera icon, action panel does not close.

I added the url in the klipperscreen.conf :
camera_url: http://127.0.0.1/webcam/?action=stream

And my stream working on : http://IP_of_my_host/webcam/?action=stream

**Comment by alfrix** [comment]
i was going to ask for the log, but i know whats going on, the vo is inverted and fails, i will also make it enter fullscreen directly since at the moment there aren't other things on the panel
