### ISSUE TITLE
Klipperscreen stuck on job status screen

### ISSUE THREAD

**Issue by xbladen** [jordanruthe/KlipperScreen#84]
Hi,
i have a proböem with klipperscreen stuck on the job status screen, it never returns to main menu.
Setup is actual clean raspian installed everything else with kiauh. Hardware is a rpi4 connected to skr1.4 in a artillary sidewinder.
Klipperscreen itself works together with klipper and fluidd, exept when it comes to printing and job-status is shown.
It does not return to main menu, but keeps on working in this state, which means it shows actual print-status, i can change to configuration and back, it keeps on blanking screen after timeout, and awakes back to life in job-status.
If i cancel print by button or in fluidd, job is canceled, but job-status still is displayed.
Restarting service KlipperScreen resets it to normal, restart klipper does not.
Following print jobs are not displayed with correct status.
I have added logfiles, of most interest maybe the last line in messages :
Feb 15 22:33:39 octopi python[584]: Attempting to add a widget with type GtkLayout to a __main__+KlipperScreen, but as a GtkBin subclass a __main__+KlipperScreen can only contain one widget at a time; it already contains a widget of type GtkLayout

This seems to show up at every try to leave the job-status panel, unfortunately i'm not so familar with python or gtk ...

[logfiles.zip](https://github.com/jordanruthe/KlipperScreen/files/5984891/logfiles.zip)

**Comment by jordanruthe** [comment]
Thanks for the log files. 0a25b4e50263e296f16a0d4fa322ce83956a4d67 should fix this issue
