### ISSUE TITLE
[BUG] installation script not installing libmpv-dev

### ISSUE THREAD

**Issue by ayesim** [jordanruthe/KlipperScreen#842]
**Describe the bug**
during fresh installation attempt. noticed that libmpv-dev is not available

**To Reproduce**
1. Go to 'KlipperScreen-install.sh'
2. edit file and find below lines.
OPTIONAL="xserver-xorg-legacy fonts-nanum fonts-ipafont, libmpv-dev"
PKGLIST="libdbus-glib-1-dev autoconf fonts-ipafont, libmpv-dev"

4. delete just before libmpv-dev ",".

**Screenshots**
missing files screenshots attached

**Logfile**

![20221211_173245](https://user-images.githubusercontent.com/26584431/207000553-cb027286-ae66-4d24-8659-c199a7fc1f48.jpg)

**Comment by ayesim** [comment]
Thank you

**Comment by Kislac** [comment]
Thank you as well, now it working
