### ISSUE TITLE
[BUG] Some Sub Menus aren`t working

### ISSUE THREAD

**Issue by yardi83** [jordanruthe/KlipperScreen#843]
**Describe the bug**

Hi,

i use klipperscreen on a Sony Xperia Android 5.0 Phone with Xserver XSDL Vers. 1.20.41 (since the newest Vers. from Playstore isn't working for me), connected with USB to a Raspberry Pi 3B and the "Actions" Menu on Home Screen (when the Printer is in idle) and the "Settings" Menu while printing aren`t working. They are there but inside is nothing. 

Did a clean install of klipperscreen and XServer a few days ago and since then they aren`t working. AFAIR both worked on a previous install with the same setup.

[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/10212355/KlipperScreen.log)

**Comment by alfrix** [comment]
you need to update, it was already fixed, sorry for the inconvenience

from your log i detected another error in the save offset function and fixed it, thank you.
