### ISSUE TITLE
Wifi Unresponsive after Klipperscreen install

### ISSUE THREAD

**Issue by Crisis64** [jordanruthe/KlipperScreen#853]
I have a Pi 3b + with Mainsail, all was was working fine, I later installed PITFT 50 & klipperscreen, & my wifi now is unresponsive, thinking it might be my install, I re-downloaded mainsail OS yesterday, setup, & tested couple of prints, all was fine with webcam, printing, ping times were sub 1 ms prior to klipperscreen software, I then installed klipperscreen, & had a constant ping going, & at the final steps of install, pings went as high as 32000 ms. I plugged ethernet cable & as soon as pi switched to that pings went back to sub 1 ms, unplugged ethernet, & as soon as wifi came back +32000 ms ping times.
Currently have ethernet cable plugged in so that I can use my klipper setup

**Comment by alfrix** [comment]
ks adds some load on the system and that may cause issues if for example your system is undervolted,  klipperscreen does not even load the wifi manager until the network panel is opened, so its probably not the issue
i would try installing `network-manager` and then use `raspi-config` to use it (advanced>network config) and reboot
