### ISSUE TITLE
[BUG] Screen wakes printer when shutdown initiated

### ISSUE THREAD

**Issue by hany** [jordanruthe/KlipperScreen#854]
**Describe the bug**
Currently I have klipper configured to initiate a power-off command after reaching a timeout, as documented in the [Moonraker configuration docs](https://moonraker.readthedocs.io/en/latest/configuration/) under **_Toggling device state from Klipper_** as follows:

`printer.cfg`:
```
[idle_timeout]
timeout: 300
gcode:
  M84
  TURN_OFF_HEATERS
  UPDATE_DELAYED_GCODE ID=delayed_printer_off DURATION=1500

[gcode_macro POWER_OFF_PRINTER]
gcode:
  {action_call_remote_method("set_device_power",
                             device="printer1",
                             state="off")}

[delayed_gcode delayed_printer_off]
initial_duration: 0.
gcode:
  {% if printer.idle_timeout.state == "Idle" %}
    POWER_OFF_PRINTER
  {% endif %}
```

In addition, I have KlipperScreen configured to automatically toggle on the power device configured in Moonraker on screen wake:

`KlipperScreen.conf`:
```
[main]
screen_on_devices: printer1
```
While KlipperScreen has the screensaver activated, when the timeout in Klipper is eventually reached, klipper properly initiates a power off of the device and shuts down. However once Klippy shuts down, KlipperScreen detects this and triggers the callback for the `shutdown` state, which in turn closes the Screensaver and wakes the screen, which in turn powers the printer back on. This is visible in the logs:

_Idle timeout reached and printer is shutdown:_
```
Dec 19 17:04:56 octopi python[869]: [power.py:process_power_changed()] - Power Device printer1: Performing stop action on bound service MoonCord
Dec 19 17:04:56 octopi KlipperScreen-start.sh[24910]: 2022-12-19 17:04:56,775 [screen.py:_websocket_callback()] - Power status changed: {'device': 'printer1', 'status': 'off', 'locked_while_printing': True, 'type': 'tplink_smartplug'}
Dec 19 17:04:57 octopi systemd[1]: MoonCord.service: Succeeded.
```

5 seconds later, Klippy shuts down, and KlipperScreen powers the printer back on:
```
Dec 19 17:05:02 octopi python[869]: [klippy_connection.py:_process_status_update()] - Klippy has shutdown
Dec 19 17:05:02 octopi python[25607]: 2022-12-19 17:05:02 octopi Client[25607] INFO [_Default] Klippy has reported a shutdown state
Dec 19 17:05:02 octopi KlipperScreen-start.sh[24910]: 2022-12-19 17:05:02,513 [printer.py:change_state()] - Changing state from 'ready' to 'shutdown'
Dec 19 17:05:02 octopi KlipperScreen-start.sh[24910]: 2022-12-19 17:05:02,513 [printer.py:change_state()] - Adding callback for state: shutdown
Dec 19 17:05:02 octopi KlipperScreen-start.sh[24910]: 2022-12-19 17:05:02,513 [screen.py:close_screensaver()] - Closing Screensaver
Dec 19 17:05:02 octopi KlipperScreen-start.sh[24910]: 2022-12-19 17:05:02,539 [screen.py:wake_screen()] - Screen wake up
Dec 19 17:05:02 octopi KlipperScreen-start.sh[24910]: 2022-12-19 17:05:02,584 [screen.py:search_power_devices()] - Found ['printer1']
Dec 19 17:05:02 octopi KlipperScreen-start.sh[24910]: 2022-12-19 17:05:02,585 [KlippyWebsocket.py:power_device_on()] - Sending machine.device_power.on {device}
Dec 19 17:05:02 octopi KlipperScreen-start.sh[24910]: 2022-12-19 17:05:02,604 [screen.py:attach_panel()] - Current panel hierarchy: splash_screen
Dec 19 17:05:02 octopi KlipperScreen-start.sh[24910]: 2022-12-19 17:05:02,613 [splash_screen.py:show_restart_buttons()] - Associated power devices: printer1
Dec 19 17:05:03 octopi python[869]: [power.py:process_power_changed()] - Power Device printer1: Performing start action on bound service MoonCord
```

I believe the issue is due to the callback for `state_shutdown` closing the screensaver which triggers the screen wake:

https://github.com/jordanruthe/KlipperScreen/blob/d2d2c82041e0f73f88ddade5dc7a00717c27ea48/screen.py#L672

**To Reproduce**
1. Configure power device in Moonraker.
2. Configure Klipper with `idle_timeout`, and setup gcode macros to initiate shutdown after timeout is reached, as documented in Moonraker's configuration docs linked above.
4. Configure KlipperScreen to power on device on screen wake.
5. Configure timeout for screensaver in KlipperScreen and allow it to be activated.
6. Printer will power off after Klipper's `idle_timeout` is reached, but power on moments after due to `shutdown` callback.

**Expected behavior**
Printer should remain off when `idle_timeout` is reached.

**Comment by alfrix** [comment]
an event wakes the screen it's by design to get attention
screen_on_devices are supposed to wake with the screen, 
this event was intended for screen backlight or some lighting and not for the printer itself
