### ISSUE TITLE
[FR] Center Screw Adjust

### ISSUE THREAD

**Issue by Roccccky** [jordanruthe/KlipperScreen#863]
Any chance to add a middle-middle (center) screw position for klipperscreen.
I have four corner screws and one in center of bed.

**Comment by Bahoue** [comment]
Maybe by adding the position of the central screw? I don't know if this is possible. Try and tell me :)

[bed_screws]
screw1: 42,40
screw1_name: front left
screw2: 42,280
screw2_name: rear left
screw3: 282,280
screw3_name: rear right
screw4: 282,40
screw4_name: front right
screw5: 150,150
screw5_name: middle

**Comment by Roccccky** [comment]
This is working for ScrewAdjust itself but not for Klipperscreeninterface
