### ISSUE TITLE
[Request] Bed-Mesh graph not avaiable...

### ISSUE THREAD

**Issue by Giadej** [jordanruthe/KlipperScreen#867]
Is it possible to view the bed-mesh as reported in the official documentation?
It is an older script or need some code to show the graphic? 

![bed_mesh](https://user-images.githubusercontent.com/80910217/212180217-90fbf86b-8f59-440f-897d-af250c9ad634.png)

**Comment by ColdBeer72** [comment]
I have just the same issue.

**Comment by alfrix** [comment]
3d graph was deprecated due to bad performace and the dependencies that it needed which created extra problems
