### ISSUE TITLE
Invalid config file Option "use_dpms" not recognized for section "[printer FlsunQQ-S_PRO]"[BUG]

### ISSUE THREAD

**Issue by qkpony** [jordanruthe/KlipperScreen#875]
After I did a update on my klipper I have been getting this error just on my screen on the printer. Invalid config file Option "use_dpms" not recognized for section "[printer FlsunQQ-S_PRO]". It came after an update. I can't seem to figure it out. Now when I try to pen any of the config files through the web browser the circle just keeps spinning like it's waiting. but IDK why I am getting this on my screen. I hope I did this correctly.

[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/10477006/KlipperScreen.log)

**Describe the bug**

**To Reproduce**
2. Click on '....

**Expected behavior**

**Screenshots**

**Logfile**

[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/10477009/KlipperScreen.log)

**Comment by qkpony** [comment]
I got it fixed. I just commented out the line for using dpms.

**Comment by alfrix** [comment]
use_dpms goes in section [main]

it's one of the options that's preferable to use directly on the ui and not force it in the config
