### ISSUE TITLE
Klipperscreen installation failed[BUG]

### ISSUE THREAD

**Issue by abhishekgyani** [jordanruthe/KlipperScreen#880]
![image](https://user-images.githubusercontent.com/55229787/215249885-da1ae792-7224-4023-8cb1-99979598782e.png)
hi, i tried adding the update manager code for klipperscreen but it is failed with the error mentioned in the screenshot. i tried install kiauh , but it is also failing. check another screenshot.
![image](https://user-images.githubusercontent.com/55229787/215249969-d6a7b772-56e1-42a4-8a6b-6a86a987f841.png)
can you please help me in rectifying the issue?

**Comment by alfrix** [comment]
you seem to be using a mirror of github which is failing for some reason, this is not  a bug of KlipperScreen
