### ISSUE TITLE
Install "completes" but service is not valid

### ISSUE THREAD

**Issue by agentnoise** [jordanruthe/KlipperScreen#892]
When installing klipperscreen it gets all the way through the install but at the end when it's trying to start the service it says `looking for '': no such file or directory found.`  I do not see any errors during the install process. 

The service can not be started manually either and the` klipperscreen.service` file in `etc/systemd/system` is empty. 

I'm installing the latest build on:
Distributor ID: Raspbian
Description:  Raspbian GNU/Linux 11 (bullseye)
Release:  11
Codename:   bullseye

**Comment by alfrix** [comment]
not useful without the install log/output since this could be caused by a failure early downloading that you didn't notice, kiauh sometimes says success but if you read above you will see that ks install script exited in error
