### ISSUE TITLE
Two screens showing

### ISSUE THREAD

**Issue by rlarudqls630** [jordanruthe/KlipperScreen#899]
Hi
I currently installed klippy screen to BTT PITFT50.
However, touch screen was now wroking properly, so I checked it with vnc but I am seeing two screens. 
How do I fix this issue?

right side that is black is extra screen 

![Screenshot 2023-02-14 at 0 46 42](https://user-images.githubusercontent.com/11022460/218504817-eb7d9c3a-a619-4379-9534-e24c6407eaf8.png)

**Comment by alfrix** [comment]
this issue tracker is for bugs or feature request of the application itself, sorry i can't help you
