### ISSUE TITLE
[BUG] Bed levelling screen scales up on on Y axis when using [bed_screws] with 3 positions

### ISSUE THREAD

**Issue by dctrjones** [jordanruthe/KlipperScreen#904]
After adding the appropriate lines in KlipperScreen.cfg to indicate the locations of the 3 [bed_screws] positions, when going to 'Bed Levelling': the screen scales up on the Y axis, pushing the lower icons off the screen.

The 3 Icons showing the bed positions are rather large, which appears to be what is changing the screen scale/resolution.

There is a visible increase in the spacing between the icons on screen left, pushing the emergency stop button almost off screen at the bottom.  

Settings are as follows:

In `printer.cfg`
```
[bed_screws]
screw1: 7, 75
screw1_name: left-middle
screw2: 107, 25
screw2_name: front-right
screw3: 107, 115
screw3_name: back-right
```

`KlipperScreen.cfg`
```
[main]
default_printer: Trinus

[printer Trinus]
screw_positions: lm, fr, br

#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# show_heater_power = True
#~# move_speed_xy = 61
#~# print_sort_dir = date_desc
#~#
```

**To Reproduce**
Within KlipperScreen click:
Configuration -> Bed Levelling

Screen then scales up on Y axis.

The bed levelling buttons perform as expected when pressing on the larger icons.

Can be reset to normal by restarting KlipperScreen.

**Expected behavior**
Screen should not scale up on Y axis when clicking Bed Levelling.

**Screenshots**
Screen is normal:
![IMG_3069](https://user-images.githubusercontent.com/22621828/221384809-8cdfc631-aaba-4154-82c7-3b3d40863e80.jpeg)

Still normal after clicking 'Configuration'
![IMG_3070](https://user-images.githubusercontent.com/22621828/221384808-697ccd4c-2c8e-4df9-b5d2-f47a1610db27.jpeg)

After clicking 'Bed Levelling', screen scales up on Y axis, pushing lower portion of canvas off the bottom of the screen.
![IMG_3071](https://user-images.githubusercontent.com/22621828/221384807-40234a82-57dc-4c64-a58a-c3f74c0758ec.jpeg)

**Logfile**
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/10832529/KlipperScreen.log)

Running on a Rpi 3B+
KlipperScreen and all associated programs are up-to-date:
![Screenshot 2023-02-25 at 18 58 31](https://user-images.githubusercontent.com/22621828/221385072-bfe737d9-4e68-4c8f-89a3-aaa90f4204ac.jpg)

**Comment by chrisfullman** [comment]
This is happening for me with 6 screws, as well; the Elegoo Neptune 3 Plus has 3 screws on each side. I have to restart Klipperscreen and not open the bed leveling screen afterwards otherwise I'm missing buttons.
