### ISSUE TITLE
[BUG] No macros in Klipperscreen

### ISSUE THREAD

**Issue by stenc55** [jordanruthe/KlipperScreen#909]
**Describe the bug**
No macros are shown in Klipperscreen. Armbian CLI on Orangepi 3LTS.
Only one showing is Load/Unload in Extrude screen.

**Expected behavior**
See macros when in macro screen

**Logfile**
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/10866014/KlipperScreen.log)

**Comment by alfrix** [comment]
can you please provide you printer.cfg or the file containing your macros sections?

**Comment by stenc55** [comment]
Renamed to .txt, Github does not allow .cfg.
Also, in printer.config kiauh macros are included and can be started form Mainsail macro section
![Posnetek zaslona 2023-03-04 213250](https://user-images.githubusercontent.com/68291385/222927484-3d2e7563-a1bb-4c3a-9153-6bd72c9578e8.png)


[kiauh_macros.txt](https://github.com/jordanruthe/KlipperScreen/files/10889621/kiauh_macros.txt)

**Comment by alfrix** [comment]
i've tested [kiauh_macros.txt](https://github.com/jordanruthe/KlipperScreen/files/10889621/kiauh_macros.txt) and it works correctly, maybe the issue is inside `pa_tuner1.cfg` please attach it so i can test it.

**Comment by stenc55** [comment]
[pa_tuner1.txt](https://github.com/jordanruthe/KlipperScreen/files/10923462/pa_tuner1.txt)

**Comment by alfrix** [comment]
it is caused by the extra space at the end of the last two macros, any extra space at the start or end will cause this
