### ISSUE TITLE
[BUG] there is no scrolling through the language selection menu.

### ISSUE THREAD

**Issue by komandrik** [jordanruthe/KlipperScreen#915]
When the font size is set to maximum, in the language selection menu you can select a language from the list only up to Polish (pl).
![image](https://user-images.githubusercontent.com/40995038/223275507-be510610-2683-4058-9fb2-90da0ff16dca.png)
![image](https://user-images.githubusercontent.com/40995038/223275663-5dde18b3-c1fa-4443-b2e9-292b153b4781.png)

When the small font is installed, in the language selection menu you can select a language from the list only up to Slovenian (sv)
![image](https://user-images.githubusercontent.com/40995038/223276036-40912e9d-ae5d-4a7f-8276-f61240109749.png)
![image](https://user-images.githubusercontent.com/40995038/223276220-13e1f643-d54a-40cb-a788-531a93c79f14.png)

The bug is that there is no scrolling of the list to the end, for example, I cannot select Ukrainian (uk), as it is not displayed under any conditions.
It is also impossible to choose Turkish and Chinese languages.

**Comment by alfrix** [comment]
this seems to be a gtk bug, since it is configured to appear as list (with scroll and arrows) and it does work on my system
