### ISSUE TITLE
GL Driver Section not available for ver. 11 (bullseye)

### ISSUE THREAD

**Issue by NikosSprocket** [jordanruthe/KlipperScreen#919]
Just an info. for updating the Wiki in the [Troubleshooting](https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/) section that Debian 11 (bullseye) does not have the **_**GL Driver**_** under the **_Advanced_** section of the **_raspi-config_** anymore.
btw changing to fkms works great.

**Comment by alfrix** [comment]
below the raspi-config mode there is the manual mode it says 

> Or:
> 
> manually edit

not a klipperscreen bug, you need to install the screen as instructed by the manufacturer
in general any screen is not working or touch is not working is not an issue with klipperscreen, remember klipperscreen is just an application, it doesn't control drivers.

**Comment by NikosSprocket** [comment]
Sorry for the confusion. It's not a bug; just the documentation on the Wiki suggests that there is a "GL Driver" option under the Advance section of "raspi-config". This is not available since Debian bullseye. See below:

![image](https://user-images.githubusercontent.com/90818362/224442805-c839fdaf-826e-45ef-a31f-040c0384405f.png)

**Comment by alfrix** [comment]
the docs need updating, but docs are correct the menu was still there in the pi3

**Comment by NikosSprocket** [comment]
Wow! I have Pi4s only and it's not!!! I will never have guest that 3 and 4 has that many differences. Good to know.

```
:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
:~ $ uname -a
Linux voron24-01 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux
```

![image](https://user-images.githubusercontent.com/90818362/224460662-929a8361-cbc1-4acf-941f-60fa9a16fa3d.png)


Below is the main menu from my 4 (
