### ISSUE TITLE
Unable to create panel: job_status "filament_diameter"[BUG]

### ISSUE THREAD

**Issue by ivvi25** [jordanruthe/KlipperScreen#924]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logfile**
Attach your [klipperscreen.log](https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/)

**Comment by ivvi25** [comment]
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/10949064/KlipperScreen.log)
![IMG_20230311_202322](https://user-images.githubusercontent.com/117710801/224503010-07bd07fb-a93c-4a9c-bbf5-4f1a33a7d414.jpg)

**Comment by DeGrandNagus** [comment]
Same issue here, OP might wanna fill out the form though.

Anyway, this happens when you start a print. Everythings fine before then.

**Comment by Geeps-SA** [comment]
Exact same thing my side but also noticed it on Z_calibrate 
![image](https://user-images.githubusercontent.com/49604828/224505437-cb5e08d0-4559-4cf3-b4ee-7c713c14341c.png)
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/10949168/KlipperScreen.log)

**Comment by ivvi25** [comment]
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/10949182/KlipperScreen.log)

**Comment by robertspark** [comment]
I have a very similar message

Unable to create panel: move 'kinematics' 

when going to the move screen, i had just updated klipperscreen today :(

I presume they are all related.

**Comment by ivvi25** [comment]
Yes, i had just updated klipperscreen today.

**Comment by ValterFerreira** [comment]
> I just installed -3 commits of the github repo and it seems to work fine (the issue arises at -2 commits, (dfe1ac8) v0.3.2-10
> 
> {if you want a fix go into terminal via ssh and type:
> cd KlipperScreen
> git checkout be473bf
> ./scripts/KlipperScreen-install.sh
> 
> and it should work fine as a temp fix


I tried but it doesn't work for me, the error remains.

**Comment by robertspark** [comment]
try 

cd KlipperScreen
git checkout HEAD~5
./scripts/KlipperScreen-install.sh

note the ~ is the tide symbol

is it ACTUALLY installing or failing at some point?
