### ISSUE TITLE
Unable to load panel after update

### ISSUE THREAD

**Issue by 3Dxcub3** [jordanruthe/KlipperScreen#925]
this error comes up on the Screen after a recent update:

Unable to load panel job_status Unable to create panel: job_status
'filament_diameter'
<img width="668" alt="Screen Shot 2023-03-11 at 21 24 15" src="https://user-images.githubusercontent.com/24828144/224519126-fd067e95-2f47-4976-9923-6de7e3991cba.png">

A solution/workaround for this error would be much appreciated.

**Comment by witem** [comment]
The same for me

**Comment by alfrix** [comment]
duplicate of #924
