### ISSUE TITLE
[BUG]Cant rotate interface in portrait mode

### ISSUE THREAD

**Issue by ffnull** [jordanruthe/KlipperScreen#939]
Hello. Im modify Creality Sermoon v1 with waveshare 4.3 DSI screen and Raspberry pi4. All works grate but interface in landscape mode. I need portrait mode. Im try to add in cmdline.txt file video=DSI-1:800x480@60,rotate=180 but it only flip display. when im set 90 - nothing happens and interface stiil in landscape. How to?

**Comment by alfrix** [comment]
not a bug, ks will detect resolution and set itself in portrait if width<height, you need to start the xserver with the correct resolution/orientation
