### ISSUE TITLE
[BUG] temp colour missing (more devices than the default colors provide)

### ISSUE THREAD

**Issue by colly05** [jordanruthe/KlipperScreen#944]
[Uploading KlipperScreen.log…]()
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/11241990/KlipperScreen.log)
Not sure if this is a bug or cfg issue. But the Home Screen I’m looking to get the colour showing on all temperatures note i have 6 temperature items 
![IMG_1589](https://user-images.githubusercontent.com/85044944/229483701-a7bd441d-69c0-4c17-b356-d9b01f9a34cb.jpeg)
All others work fine and even octopus works to hide the colour on the graph but it doesn’t show colour as the pic.

**Comment by colly05** [comment]
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/11240307/KlipperScreen.log)

**Comment by alfrix** [comment]
i don't see any errors does other themes work?

**Comment by colly05** [comment]
there is no issues apart from the colour not showing if i remove say the  ebb36 in printer.cfg it comes back. so im unsure if its an issue with how many items ? the colour shows on the graph fine and goes like the others but does not show next to it ?
thanks

**Comment by colly05** [comment]
it seams to follow which is last in the printer.cfg ?
