### ISSUE TITLE
move speed too low ?

### ISSUE THREAD

**Issue by simonvez** [jordanruthe/KlipperScreen#95]
when using the move command on the screen it moves at like 5mm/s. Is there a way to boost that up ? or is that done through klipper config ? I cant find anything about it

**Comment by jordanruthe** [comment]
I can make the speeds configurable in a future update

**Comment by simonvez** [comment]
awesome thanks !! Let me know when its available and ill buy you another coffee :)

**Comment by robvoi** [comment]
Would be great.
I think one issue is, that the move speed stays slow after moving Z. (think this is it, not really tried to reproduce it)
After a restart it is ok. Sometimes it goes to snake mode.
