### ISSUE TITLE
[BUG] service restart is not working

### ISSUE THREAD

**Issue by bob-u** [jordanruthe/KlipperScreen#950]
**Describe the bug**

When KlipperScreen restarts it does not restart the service.

**To Reproduce**

I have added to KlipperScreen.conf the following:

> [main]
> service = vncserver@5

however, KlipperScreen does not restart the vncserver@5 service when I change the font size, for example.   I can start, stop view status of vncserver@5 service from the terminal:
`
bobby@mint:~/.vnc$ systemctl status vncserver@5
● vncserver@5.service - Remote desktop service for Klipperscreen(VNC)
     Loaded: loaded (/etc/systemd/system/vncserver@.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-04-13 09:53:30 EDT; 1min 23s ago
    Process: 16498 ExecStartPre=/usr/bin/vncserver -kill :5 > /dev/null 2>&1 (code=exited, status=1/FAILURE)
    Process: 16501 ExecStart=/usr/bin/vncserver :5 -geometry 480x320 -depth 24 -pixelformat bgr565 -passwordfile /home/bobby/.vnc/passwd -localhost=0 (code=exited, status=0/SUCCESS)
   Main PID: 16508 (Xtigervnc)
      Tasks: 15 (limit: 4561)
     Memory: 65.8M
        CPU: 1.236s
     CGroup: /system.slice/system-vncserver.slice/vncserver@5.service
             ├─16507 /usr/bin/perl /usr/bin/vncserver :5 -geometry 480x320 -depth 24 -pixelformat bgr565 -passwordfile /home/bobby/.vnc/passwd -localhost=0
             ├─16508 /usr/bin/Xtigervnc :5 -localhost=0 -desktop "mint:5 (bobby)" -rfbport 5905 -PasswordFile /home/bobby/.vnc/passwd -SecurityTypes VncAuth,TLSVnc -auth /home/bobby/.Xauthority -geometry 48>
             ├─16512 /home/bobby/.KlipperScreen-env/bin/python /home/bobby/KlipperScreen/screen.py
             ├─16517 dbus-launch --autolaunch 8283e071490343188007b10cb544d01b --binary-syntax --close-stderr
             ├─16518 /usr/bin/dbus-daemon --syslog-only --fork --print-pid 5 --print-address 7 --session
             ├─16520 /usr/libexec/at-spi-bus-launcher
             ├─16525 /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 11 --address=unix:path=/home/bobby/.cache/at-spi/bus_5
             └─16547 /usr/libexec/at-spi2-registryd --use-gnome-session

Apr 13 09:53:27 mint vncserver[16507]: New Xtigervnc server 'mint:5 (bobby)' on port 5905 for display :5.
Apr 13 09:53:27 mint vncserver[16507]: Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /home/bobby/.vnc/passwd mint:5 to connect to the VNC server.
Apr 13 09:53:27 mint dbus-daemon[16518]: [session uid=1000 pid=16516] AppArmor D-Bus mediation is enabled
Apr 13 09:53:27 mint dbus-daemon[16518]: [session uid=1000 pid=16516] Activating service name='org.a11y.Bus' requested by ':1.0' (uid=1000 pid=16512 comm="/home/bobby/.KlipperScreen-env/bin/python /home/t>
Apr 13 09:53:27 mint dbus-daemon[16518]: [session uid=1000 pid=16516] Successfully activated service 'org.a11y.Bus'
Apr 13 09:53:28 mint org.a11y.Bus[16525]: dbus-daemon[16525]: Activating service name='org.a11y.atspi.Registry' requested by ':1.0' (uid=1000 pid=16512 comm="/home/bobby/.KlipperScreen-env/bin/python /hom>
Apr 13 09:53:28 mint org.a11y.Bus[16525]: dbus-daemon[16525]: Successfully activated service 'org.a11y.atspi.Registry'
Apr 13 09:53:28 mint org.a11y.Bus[16547]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
Apr 13 09:53:30 mint systemd[1]: vncserver@5.service: Supervising process 16508 which is not our child. We'll most likely not notice when it exits.
Apr 13 09:53:30 mint systemd[1]: Started Remote desktop service for Klipperscreen(VNC).
bobby@mint:~/.vnc$ systemctl stop vncserver@5
bobby@mint:~/.vnc$ systemctl status vncserver@5
○ vncserver@5.service - Remote desktop service for Klipperscreen(VNC)
     Loaded: loaded (/etc/systemd/system/vncserver@.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Thu 2023-04-13 09:55:06 EDT; 5s ago
    Process: 16498 ExecStartPre=/usr/bin/vncserver -kill :5 > /dev/null 2>&1 (code=exited, status=1/FAILURE)
    Process: 16501 ExecStart=/usr/bin/vncserver :5 -geometry 480x320 -depth 24 -pixelformat bgr565 -passwordfile /home/bobby/.vnc/passwd -localhost=0 (code=exited, status=0/SUCCESS)
    Process: 16586 ExecStop=/usr/bin/vncserver -kill :5 (code=exited, status=0/SUCCESS)
   Main PID: 16508
        CPU: 1.381s

Apr 13 09:53:28 mint org.a11y.Bus[16547]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
Apr 13 09:53:30 mint systemd[1]: vncserver@5.service: Supervising process 16508 which is not our child. We'll most likely not notice when it exits.
Apr 13 09:53:30 mint systemd[1]: Started Remote desktop service for Klipperscreen(VNC).
Apr 13 09:55:06 mint systemd[1]: Stopping Remote desktop service for Klipperscreen(VNC)...
Apr 13 09:55:06 mint org.a11y.Bus[16547]: X connection to :5 broken (explicit kill or server shutdown).
Apr 13 09:55:06 mint vncserver[16586]: Killing Xtigervnc process ID 16508... success!
Apr 13 09:55:06 mint systemd[1]: vncserver@5.service: Killing process 16508 (n/a) with signal SIGKILL.
Apr 13 09:55:06 mint systemd[1]: vncserver@5.service: Deactivated successfully.
Apr 13 09:55:06 mint systemd[1]: Stopped Remote desktop service for Klipperscreen(VNC).
Apr 13 09:55:06 mint systemd[1]: vncserver@5.service: Consumed 1.381s CPU time.
bobby@mint:~/.vnc$ systemctl start vncserver@5
bobby@mint:~/.vnc$ systemctl status vncserver@5
● vncserver@5.service - Remote desktop service for Klipperscreen(VNC)
     Loaded: loaded (/etc/systemd/system/vncserver@.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-04-13 09:55:24 EDT; 7s ago
    Process: 16603 ExecStartPre=/usr/bin/vncserver -kill :5 > /dev/null 2>&1 (code=exited, status=1/FAILURE)
    Process: 16606 ExecStart=/usr/bin/vncserver :5 -geometry 480x320 -depth 24 -pixelformat bgr565 -passwordfile /home/bobby/.vnc/passwd -localhost=0 (code=exited, status=0/SUCCESS)
   Main PID: 16613 (Xtigervnc)
      Tasks: 16 (limit: 4561)
     Memory: 65.8M
        CPU: 1.100s
     CGroup: /system.slice/system-vncserver.slice/vncserver@5.service
             ├─16612 /usr/bin/perl /usr/bin/vncserver :5 -geometry 480x320 -depth 24 -pixelformat bgr565 -passwordfile /home/bobby/.vnc/passwd -localhost=0
             ├─16613 /usr/bin/Xtigervnc :5 -localhost=0 -desktop "mint:5 (bobby)" -rfbport 5905 -PasswordFile /home/bobby/.vnc/passwd -SecurityTypes VncAuth,TLSVnc -auth /home/bobby/.Xauthority -geometry 48>
             ├─16616 /home/bobby/.KlipperScreen-env/bin/python /home/bobby/KlipperScreen/screen.py
             ├─16621 dbus-launch --autolaunch 8283e071490343188007b10cb544d01b --binary-syntax --close-stderr
             ├─16622 /usr/bin/dbus-daemon --syslog-only --fork --print-pid 5 --print-address 7 --session
             ├─16624 /usr/libexec/at-spi-bus-launcher
             ├─16629 /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 11 --address=unix:path=/home/bobby/.cache/at-spi/bus_5
             └─16651 /usr/libexec/at-spi2-registryd --use-gnome-session

Apr 13 09:55:21 mint vncserver[16612]: New Xtigervnc server 'mint:5 (bobby)' on port 5905 for display :5.
Apr 13 09:55:21 mint vncserver[16612]: Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /home/bobby/.vnc/passwd mint:5 to connect to the VNC server.
Apr 13 09:55:21 mint dbus-daemon[16622]: [session uid=1000 pid=16620] AppArmor D-Bus mediation is enabled
Apr 13 09:55:21 mint dbus-daemon[16622]: [session uid=1000 pid=16620] Activating service name='org.a11y.Bus' requested by ':1.0' (uid=1000 pid=16616 comm="/home/bobby/.KlipperScreen-env/bin/python /home/t>
Apr 13 09:55:21 mint dbus-daemon[16622]: [session uid=1000 pid=16620] Successfully activated service 'org.a11y.Bus'
Apr 13 09:55:21 mint org.a11y.Bus[16629]: dbus-daemon[16629]: Activating service name='org.a11y.atspi.Registry' requested by ':1.0' (uid=1000 pid=16616 comm="/home/bobby/.KlipperScreen-env/bin/python /hom>
Apr 13 09:55:21 mint org.a11y.Bus[16629]: dbus-daemon[16629]: Successfully activated service 'org.a11y.atspi.Registry'
Apr 13 09:55:21 mint org.a11y.Bus[16651]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
Apr 13 09:55:24 mint systemd[1]: vncserver@5.service: Supervising process 16613 which is not our child. We'll most likely not notice when it exits.
Apr 13 09:55:24 mint systemd[1]: Started Remote desktop service for Klipperscreen(VNC).`

**Expected behavior**

I expect vncserver@5 to restart 

**Screenshots**

**Logfile**
Attach your [klipperscreen.log](https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/)

**Comment by bob-u** [comment]
I setup systemd to autostart the vncserver and keep on restarting it instead.  Anyway, could you explain what is the expected behavior for service = <service name>?  I could not find it in the documentation but saw it being mentioned on discourse.

**Comment by alfrix** [comment]
the option service was deprecated #656 
ks will warn you that is not recognized at startup
> I setup systemd to autostart the vncserver and keep on restarting it instead. 

ks is configured to restart always by default too

another way would be adding ` After=vncserver`  and ` Requires=vncserver`  to the ks service file if you need the dependency
