### ISSUE TITLE
[BUG] ETA and print time different from Mainsail

### ISSUE THREAD

**Issue by tcurdt** [jordanruthe/KlipperScreen#957]
**Describe the bug**

KlipperScreen shows very different time to finish/ETA values than Mainsail.
At least at the beginning of the print the times are off by a factor of 3 or more.

**Expected behavior**

See the same times as in Mainsail.

**Comment by alfrix** [comment]
you can configure the time estimation method in the settings
"auto"  will use slicer time up to 14% and then use weighted arithmetic with the other methods

if your print time is very off at the start it means that your slicer is doing a very bad job estimating, take a look at https://github.com/Annex-Engineering/klipper_estimator if you want better results, if you use this then the prefered method would be setting the time estimate to slicer

**Comment by tcurdt** [comment]
This feels a little off.
Once I realized I had to configure this from the UI (and not in the configuration) I switch to "slicer" and things got better.
🤷‍♂️
