### ISSUE TITLE
KlipperScreen goes back to home screen even when job is still running

### ISSUE THREAD

**Issue by michelluccote** [jordanruthe/KlipperScreen#96]
On multiple occasions I have KlipperScreen go back to the home screen even when a job is still running. It seem ok on Fluidd but KlipperScreen no longer things a job is running which means I don't have the menus to adjust z-offset while it's running.

FYI I did have to reduce the size of the moonraker.log file but it should have enough history to work with. 

[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/6039787/KlipperScreen.log)
[klippy.log](https://github.com/jordanruthe/KlipperScreen/files/6039785/klippy.log)
[moonraker.log](https://github.com/jordanruthe/KlipperScreen/files/6039782/moonraker.log)

**Comment by jordanruthe** [comment]
Thanks for the log files. I think I may have gotten this one corrected based off of what I found.
