### ISSUE TITLE
[FR] Fully Adapted PT_BR Translation

### ISSUE THREAD

**Issue by rafaelSwi** [jordanruthe/KlipperScreen#961]
Hello, I'm born and raised in Brazil, with a good knowledge of the Portuguese language, and I've decided, as a way of saying "thank you" to the KlipperScreen Team, to improve the Portuguese translation.

In no way am I judging the quality of the translation already used, as the Portuguese language is indeed complex, and using methods such as Online Translators to speed up the process is a great alternative for the development team. However, the translation has several problems, mainly related to literal translations, which do not fit the context of the situations in which they were inserted.

This new translation is completely adapted to Brazilian Portuguese, both for understanding the language and for size in its appropriate Text boxes.

Some words do not have a direct translation into Portuguese, a good example is "_Home All_". This phrase "Home All" has no meaning in the Portuguese language, as it would indicate that everyone clicking the button should go to their homes. Because of this, some phrases were re-interpreted, in a way that, in fact, that they may vary in other softwares, however, it serves the purpose of interpreting its role for the user.

The ".mo" file was converted using an online converter, and I also don't know how to check the file for "watermarks", however if that is an issue, I will obviously be attaching the clean ".po" file.

I just attached a small message in the ".po" file in the form of a comment, at the beginning of the file, with my name. Feel free to format and edit the file however you like, I just did it on instinct.

_Note: I discovered that GitHub won't let me attach ".po" or ".mo" files, so I uploaded a ".zip" file._

[pt.zip](https://github.com/jordanruthe/KlipperScreen/files/11338511/pt.zip)

**Comment by alfrix** [comment]
thank you
