### ISSUE TITLE
[FR] Match shutdown action to Moonraker, Restart to Mainsail

### ISSUE THREAD

**Issue by tinymachines3d** [jordanruthe/KlipperScreen#963]
**description of issue**
When using some non RPI SBCs (Le Potato in this case) shutdown from KlipperScreen just reboots the device instead of shutting down. This is due to the shutdown method used / command sent to the linux device. 

Setting shutdown_action: halt in moonraker.conf allows proper shutdown from mainsail. 

**Describe the solution you'd like**
It seems KlipperScreen is using sudo poweroff to shutdown, sudo shutdown -h now being an option could be a toggle in settings>shutdown method

_OR_

gather info from moonraker.conf and use the shutdown_action: called there. 
<img width="530" alt="image" src="https://user-images.githubusercontent.com/28379694/235310519-5cf9d3c3-3a2a-4147-b3e7-ec7fb07ca97c.png">

**Describe alternatives you've considered**
Using shutdown from mainsail 

**Additional context**
Is there another way to set this that is not otherwise documented?

**Comment by alfrix** [comment]
while connected to moonraker the shutdown action is performed by moonraker and when selecting "printer" in the system panel shutdown/reboot options
otherwise ks will send `systemctl poweroff` and  ` systemctl reboot` if that doesn't work is a bug of the OS, i will not make patches to workaround broken platforms

**Comment by dotorg** [comment]
For what its worth, not all Linux systems use systemd. _systemctl poweroff_ and _systemctl reboot_ not working isn't an OS bug. The low-level standard Linux command that works on all platforms is the shutdown command, which works on systems that don't use systemd as well. If you wanted to ensure compatibility, that's the command to use -- _shutdown -h_ or _shutdown -r_ 

A significant percentage of distributions targeted at minimal installations don't use it.
