### ISSUE TITLE
[BUG] Touch points are not in sync with the screen icons

### ISSUE THREAD

**Issue by Gil80** [jordanruthe/KlipperScreen#966]
**Describe the bug**
Touch screen has different offset values

**To Reproduce**
I hat to rotate the screen 180.

**Expected behavior**
Touch points to register correctly

I use RPi 3B with a DSI display.
I rotated the screen using the /boot/config.txt file 
```
[all]
display_rotate=2
```
The screen rotated correclty, but the touch points didn't rotate accordingly.
I added this: `180° (Inverts X and Y): -1 0 1 0 -1 1 0 0 1` to `/usr/share/X11/xorg.conf.d/40-libinput.conf` but if I do this, then klipperscreen is stuck in console mode.

**Comment by alfrix** [comment]
not a bug of ks, you need to configure your touchscreen properly,  this issue tracker is for bugs or feature request of the application itself
