### ISSUE TITLE
No Screens found using CB1 and BTT SPI Screen

### ISSUE THREAD

**Issue by Doormat1** [jordanruthe/KlipperScreen#968]
Ive followed the installation instructions for klipperscreen using KIUAH and have uncommented the relavent parts in boardenv.txt but the screen is just showing the console and stuck at the login part. Any suggestions how to move from here?

**Comment by alfrix** [comment]
the issue tracker is for bugs or feature requests of the application, you need to install your screen, unfortunately i can't help you with that
