### ISSUE TITLE
Show Chamber Temperature ?

### ISSUE THREAD

**Issue by simonvez** [jordanruthe/KlipperScreen#97]
Hi Jordan, It would be cool to see chamber temp somewhere on the screen :)  I dont know if its possible or not. Just a suggestion here. thanks again

**Comment by jordanruthe** [comment]
With the updates I pushed a few days ago, heater_generic devices should show up and be controllable.

**Comment by simonvez** [comment]
I dont have hearers... just a temp sensor :)

**Comment by jordanruthe** [comment]
Fair point. I'll look at adding this soon

**Comment by simonvez** [comment]
you rock !!

**Comment by jordanruthe** [comment]
The temperature_sensor has now been implemented.

**Comment by th3fallen** [comment]
@jordanruthe could you please elaborate how you control them? i've attempted to add `chamber` to my preset as well as `heater_generic` but none yeild success it always sets it to 0
