### ISSUE TITLE
Display sometimes gets stuck at cancelling print [BUG]

### ISSUE THREAD

**Issue by Matszwe02** [jordanruthe/KlipperScreen#974]
**Describe the bug**
When I press "restart" when I cancelled the print, display doesn't always go to "printing" state

**To Reproduce**
1. Start some print
2. Cancel print
3. Press "Restart print" before the cancel print macro finished executing
4. Printer starts printing, display stays at "cancelling"

**Expected behavior**

**Screenshots**

**Logfile**
Attach your [klipperscreen.log](https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/)

**Comment by alfrix** [comment]
closing since no log was provided, i suspect this was probably fixed by https://github.com/jordanruthe/KlipperScreen/commit/4db7fd288cf91c4e6639bf492fd3cee7ccf2dcc0
