### ISSUE TITLE
[FR] Troubleshooting guide, add disabling the TV out on Pi3

### ISSUE THREAD

**Issue by shiftingtech** [jordanruthe/KlipperScreen#983]
So I was recently setting up klipperscreen on a pi3 system, and once I got everything else working, had the interesting discovery that X was trying to output on my touch screen AND the tv out.

Video wise, this didn't really matter, but the actual TOUCH events for the touch screen got spread out across both, causing all the touch events  to be *grossly* mis-calibrated.

I'd suggest adding an entry to troubleshooting, recommending 
"enable_tvout=0"  in config.txt on pi3 and older.

**Comment by alfrix** [comment]
i agree that the troubleshooting guide needs more work, i will give this priority since i've seen people having issues with OS updates

**Comment by alfrix** [comment]
added to the docs eb24987b27c63526e41b6b2269ba49f6738bebe4
