### ISSUE TITLE
Autodelete log similar to crowsnest

### ISSUE THREAD

**Issue by MikeEitel** [jordanruthe/KlipperScreen#988]
**Is your feature request related to a problem? Please describe.**

**The log is growing but I see no real value in it.**

**Describe the solution you'd like**

**Parameter in config file.**

**Describe alternatives you've considered**

None, but delete by hand

**Additional context**

**Comment by alfrix** [comment]
> The log is growing

there is no need for this, the log will rotate reaching 4MB with one backup, this is a total of 8MB

> I see no real value in it.

the log is handy when you encounter an issue, usually you may not know when this will happen

as an alternative you can make the log folder a tmpfs (ramdisk) this will prolong the life of the drive and delete the logs in a reboot, but as said logs are useful to troubleshoot
