### ISSUE TITLE
System date and time

### ISSUE THREAD

**Issue by MSergW** [jordanruthe/KlipperScreen#99]
Hi!
Can be added to the top line, the side of the printer's name, the system date and time?

**Comment by jordanruthe** [comment]
The printer's name will be added once the multiple printers pull request is merged. Let me contemplate the date/time and how I would like to implement that.

**Comment by MSergW** [comment]
top - right ? :)

**Comment by jordanruthe** [comment]
Hah. More like, should there be options for time only, or date and time, or none of the above, and how to minimize gtk calls.

**Comment by jordanruthe** [comment]
a0de521631885e0dde474d48ff9cd7564fec9173 implements this
